// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Connection {
  final String id;
  final String host;
  final String network;
  final String connType;
  final String sourceIp;
  final int sourcePort;
  final String destinationIp;
  final int destinationPort;
  final String inboundIp;
  final int inboundPort;
  final String inboundName;
  final String dnsMode;
  final int uid;
  final String process;
  final String processPath;
  final String specialProxy;
  final String specialRules;
  final String remoteDestination;
  final String sniffHost;
  final String rule;
  final String rulePayload;
  final List<String> chains;
  final List<String> connectionLogs;
  final BigInt upload;
  final BigInt download;
  final BigInt uploadSpeed;
  final BigInt downloadSpeed;
  final String start;
  final bool isClosed;

  const Connection({
    required this.id,
    required this.host,
    required this.network,
    required this.connType,
    required this.sourceIp,
    required this.sourcePort,
    required this.destinationIp,
    required this.destinationPort,
    required this.inboundIp,
    required this.inboundPort,
    required this.inboundName,
    required this.dnsMode,
    required this.uid,
    required this.process,
    required this.processPath,
    required this.specialProxy,
    required this.specialRules,
    required this.remoteDestination,
    required this.sniffHost,
    required this.rule,
    required this.rulePayload,
    required this.chains,
    required this.connectionLogs,
    required this.upload,
    required this.download,
    required this.uploadSpeed,
    required this.downloadSpeed,
    required this.start,
    required this.isClosed,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      host.hashCode ^
      network.hashCode ^
      connType.hashCode ^
      sourceIp.hashCode ^
      sourcePort.hashCode ^
      destinationIp.hashCode ^
      destinationPort.hashCode ^
      inboundIp.hashCode ^
      inboundPort.hashCode ^
      inboundName.hashCode ^
      dnsMode.hashCode ^
      uid.hashCode ^
      process.hashCode ^
      processPath.hashCode ^
      specialProxy.hashCode ^
      specialRules.hashCode ^
      remoteDestination.hashCode ^
      sniffHost.hashCode ^
      rule.hashCode ^
      rulePayload.hashCode ^
      chains.hashCode ^
      connectionLogs.hashCode ^
      upload.hashCode ^
      download.hashCode ^
      uploadSpeed.hashCode ^
      downloadSpeed.hashCode ^
      start.hashCode ^
      isClosed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Connection &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          host == other.host &&
          network == other.network &&
          connType == other.connType &&
          sourceIp == other.sourceIp &&
          sourcePort == other.sourcePort &&
          destinationIp == other.destinationIp &&
          destinationPort == other.destinationPort &&
          inboundIp == other.inboundIp &&
          inboundPort == other.inboundPort &&
          inboundName == other.inboundName &&
          dnsMode == other.dnsMode &&
          uid == other.uid &&
          process == other.process &&
          processPath == other.processPath &&
          specialProxy == other.specialProxy &&
          specialRules == other.specialRules &&
          remoteDestination == other.remoteDestination &&
          sniffHost == other.sniffHost &&
          rule == other.rule &&
          rulePayload == other.rulePayload &&
          chains == other.chains &&
          connectionLogs == other.connectionLogs &&
          upload == other.upload &&
          download == other.download &&
          uploadSpeed == other.uploadSpeed &&
          downloadSpeed == other.downloadSpeed &&
          start == other.start &&
          isClosed == other.isClosed;
}

/// Aggregate of all active connections sharing one process or source IP.
class ConnectionGroup {
  final String key;
  final String label;
  final String process;
  final String processPath;
  final String sourceIp;
  final int count;
  final BigInt upload;
  final BigInt download;
  final BigInt uploadSpeed;
  final BigInt downloadSpeed;

  const ConnectionGroup({
    required this.key,
    required this.label,
    required this.process,
    required this.processPath,
    required this.sourceIp,
    required this.count,
    required this.upload,
    required this.download,
    required this.uploadSpeed,
    required this.downloadSpeed,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      label.hashCode ^
      process.hashCode ^
      processPath.hashCode ^
      sourceIp.hashCode ^
      count.hashCode ^
      upload.hashCode ^
      download.hashCode ^
      uploadSpeed.hashCode ^
      downloadSpeed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionGroup &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          label == other.label &&
          process == other.process &&
          processPath == other.processPath &&
          sourceIp == other.sourceIp &&
          count == other.count &&
          upload == other.upload &&
          download == other.download &&
          uploadSpeed == other.uploadSpeed &&
          downloadSpeed == other.downloadSpeed;
}

/// Sort key for the process-group list. Mirrors Dart's `ConnectionGroupSort`.
enum ConnectionGroupSort {
  name,
  count,
  upload,
  download,
  uploadSpeed,
  downloadSpeed,
}

class ConnectionsFrame {
  final int activeCount;
  final int closedCount;
  final ConnectionsTotals totals;

  /// True for the first frame after each WS connect or reconnect.
  final bool isInitial;

  const ConnectionsFrame({
    required this.activeCount,
    required this.closedCount,
    required this.totals,
    required this.isInitial,
  });

  @override
  int get hashCode =>
      activeCount.hashCode ^
      closedCount.hashCode ^
      totals.hashCode ^
      isInitial.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionsFrame &&
          runtimeType == other.runtimeType &&
          activeCount == other.activeCount &&
          closedCount == other.closedCount &&
          totals == other.totals &&
          isInitial == other.isInitial;
}

/// Which list a window slice is drawn from.
enum ConnectionsListKind { active, closed }

/// Sort key for the connections list. Mirrors Dart's `ConnectionsSort`.
enum ConnectionsSort {
  time,
  upload,
  download,
  uploadSpeed,
  downloadSpeed,
  process,
}

class ConnectionsTotals {
  final BigInt upload;
  final BigInt download;
  final BigInt memory;

  const ConnectionsTotals({
    required this.upload,
    required this.download,
    required this.memory,
  });

  @override
  int get hashCode => upload.hashCode ^ download.hashCode ^ memory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionsTotals &&
          runtimeType == other.runtimeType &&
          upload == other.upload &&
          download == other.download &&
          memory == other.memory;
}
