// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class MemorySample {
  final BigInt inuse;
  final BigInt oslimit;

  const MemorySample({required this.inuse, required this.oslimit});

  @override
  int get hashCode => inuse.hashCode ^ oslimit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemorySample &&
          runtimeType == other.runtimeType &&
          inuse == other.inuse &&
          oslimit == other.oslimit;
}

class TrafficSample {
  final BigInt up;
  final BigInt down;
  final BigInt upTotal;
  final BigInt downTotal;

  const TrafficSample({
    required this.up,
    required this.down,
    required this.upTotal,
    required this.downTotal,
  });

  @override
  int get hashCode =>
      up.hashCode ^ down.hashCode ^ upTotal.hashCode ^ downTotal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrafficSample &&
          runtimeType == other.runtimeType &&
          up == other.up &&
          down == other.down &&
          upTotal == other.upTotal &&
          downTotal == other.downTotal;
}
