// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'target.dart';
import 'types.dart';

Future<String> connections({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiConnectionsConnections(target: target);

Future<void> closeConnection({
  required BackendTarget target,
  required String id,
}) => RustLib.instance.api.crateBackendApiConnectionsCloseConnection(
  target: target,
  id: id,
);

Future<void> closeAllConnections({required BackendTarget target}) => RustLib
    .instance
    .api
    .crateBackendApiConnectionsCloseAllConnections(target: target);

Future<void> closeConnectionsByChain({
  required BackendTarget target,
  required String chain,
}) => RustLib.instance.api.crateBackendApiConnectionsCloseConnectionsByChain(
  target: target,
  chain: chain,
);

Future<void> closeConnectionsByGroup({
  required BackendTarget target,
  required String group,
}) => RustLib.instance.api.crateBackendApiConnectionsCloseConnectionsByGroup(
  target: target,
  group: group,
);

Stream<ConnectionsFrame> connectionsStream({
  required BackendTarget target,
  required int intervalMs,
}) => RustLib.instance.api.crateBackendApiConnectionsConnectionsStream(
  target: target,
  intervalMs: intervalMs,
);

Future<List<Connection>> fetchConnectionWindow({
  required BackendTarget target,
  required int intervalMs,
  required ConnectionsListKind kind,
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateBackendApiConnectionsFetchConnectionWindow(
  target: target,
  intervalMs: intervalMs,
  kind: kind,
  offset: offset,
  limit: limit,
);

Future<List<ConnectionGroup>> fetchConnectionGroups({
  required BackendTarget target,
  required int intervalMs,
  required ConnectionsListKind kind,
  required ConnectionGroupSort sort,
  required bool asc,
}) => RustLib.instance.api.crateBackendApiConnectionsFetchConnectionGroups(
  target: target,
  intervalMs: intervalMs,
  kind: kind,
  sort: sort,
  asc: asc,
);

Future<List<Connection>> fetchConnectionGroupMembers({
  required BackendTarget target,
  required int intervalMs,
  required ConnectionsListKind kind,
  required String group,
  required int limit,
}) =>
    RustLib.instance.api.crateBackendApiConnectionsFetchConnectionGroupMembers(
      target: target,
      intervalMs: intervalMs,
      kind: kind,
      group: group,
      limit: limit,
    );

Future<void> setConnectionsSort({
  required BackendTarget target,
  required int intervalMs,
  required ConnectionsSort sort,
  required bool asc,
}) => RustLib.instance.api.crateBackendApiConnectionsSetConnectionsSort(
  target: target,
  intervalMs: intervalMs,
  sort: sort,
  asc: asc,
);

Future<void> clearClosedConnections({
  required BackendTarget target,
  required int intervalMs,
}) => RustLib.instance.api.crateBackendApiConnectionsClearClosedConnections(
  target: target,
  intervalMs: intervalMs,
);

Future<void> clearClosedConnectionsByGroup({
  required BackendTarget target,
  required int intervalMs,
  required String group,
}) => RustLib.instance.api
    .crateBackendApiConnectionsClearClosedConnectionsByGroup(
      target: target,
      intervalMs: intervalMs,
      group: group,
    );

Future<void> stopTargetStreams({required BackendTarget target}) => RustLib
    .instance
    .api
    .crateBackendApiConnectionsStopTargetStreams(target: target);
