// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'target.dart';
import 'types.dart';

Future<String> controllerConnections({required BackendTarget target}) => RustLib
    .instance
    .api
    .crateBackendApiConnectionsControllerConnections(target: target);

Future<void> controllerCloseConnection({
  required BackendTarget target,
  required String id,
}) => RustLib.instance.api.crateBackendApiConnectionsControllerCloseConnection(
  target: target,
  id: id,
);

Future<void> controllerCloseAllConnections({required BackendTarget target}) =>
    RustLib.instance.api
        .crateBackendApiConnectionsControllerCloseAllConnections(
          target: target,
        );

Future<void> controllerCloseConnectionsByChain({
  required BackendTarget target,
  required String chain,
}) => RustLib.instance.api
    .crateBackendApiConnectionsControllerCloseConnectionsByChain(
      target: target,
      chain: chain,
    );

Future<void> controllerCloseConnectionsByGroup({
  required BackendTarget target,
  required String group,
}) => RustLib.instance.api
    .crateBackendApiConnectionsControllerCloseConnectionsByGroup(
      target: target,
      group: group,
    );

Stream<ConnectionsFrame> controllerConnectionsStream({
  required BackendTarget target,
  required int intervalMs,
  required int closedCapacity,
}) =>
    RustLib.instance.api.crateBackendApiConnectionsControllerConnectionsStream(
      target: target,
      intervalMs: intervalMs,
      closedCapacity: closedCapacity,
    );

Future<ConnectionWindow> controllerFetchConnectionWindow({
  required BackendTarget target,
  required int intervalMs,
  required ConnectionsListKind kind,
  required int offset,
  required int limit,
  required String query,
}) => RustLib.instance.api
    .crateBackendApiConnectionsControllerFetchConnectionWindow(
      target: target,
      intervalMs: intervalMs,
      kind: kind,
      offset: offset,
      limit: limit,
      query: query,
    );

Future<ConnectionStats?> controllerFetchConnectionStatsById({
  required BackendTarget target,
  required int intervalMs,
  required String id,
}) => RustLib.instance.api
    .crateBackendApiConnectionsControllerFetchConnectionStatsById(
      target: target,
      intervalMs: intervalMs,
      id: id,
    );

Future<List<ConnectionGroup>> controllerFetchConnectionGroups({
  required BackendTarget target,
  required int intervalMs,
  required ConnectionsListKind kind,
  required ConnectionGroupSort sort,
  required bool asc,
  required String query,
}) => RustLib.instance.api
    .crateBackendApiConnectionsControllerFetchConnectionGroups(
      target: target,
      intervalMs: intervalMs,
      kind: kind,
      sort: sort,
      asc: asc,
      query: query,
    );

Future<List<Connection>> controllerFetchConnectionGroupMembers({
  required BackendTarget target,
  required int intervalMs,
  required ConnectionsListKind kind,
  required String group,
  required int limit,
  required String query,
}) => RustLib.instance.api
    .crateBackendApiConnectionsControllerFetchConnectionGroupMembers(
      target: target,
      intervalMs: intervalMs,
      kind: kind,
      group: group,
      limit: limit,
      query: query,
    );

Future<void> controllerSetConnectionsSort({
  required BackendTarget target,
  required int intervalMs,
  required ConnectionsSort sort,
  required bool asc,
}) =>
    RustLib.instance.api.crateBackendApiConnectionsControllerSetConnectionsSort(
      target: target,
      intervalMs: intervalMs,
      sort: sort,
      asc: asc,
    );

Future<void> controllerClearClosedConnections({
  required BackendTarget target,
  required int intervalMs,
}) => RustLib.instance.api
    .crateBackendApiConnectionsControllerClearClosedConnections(
      target: target,
      intervalMs: intervalMs,
    );

Future<void> controllerClearClosedConnectionsByGroup({
  required BackendTarget target,
  required int intervalMs,
  required String group,
}) => RustLib.instance.api
    .crateBackendApiConnectionsControllerClearClosedConnectionsByGroup(
      target: target,
      intervalMs: intervalMs,
      group: group,
    );

Future<void> controllerStopTargetStreams({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiConnectionsControllerStopTargetStreams(
      target: target,
    );
