// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'target.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `bool_value`, `core_config_from_value`, `patch_config_value`, `string_list_value`, `string_value`, `u32_value`, `update_config`

Future<ControllerConfig> controllerConfigs({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiControlControllerConfigs(
      target: target,
    );

Future<void> controllerSetConfigMode({
  required BackendTarget target,
  required String mode,
}) => RustLib.instance.api.crateBackendApiControlControllerSetConfigMode(
  target: target,
  mode: mode,
);

Future<void> controllerSetConfigLogLevel({
  required BackendTarget target,
  required String level,
}) => RustLib.instance.api.crateBackendApiControlControllerSetConfigLogLevel(
  target: target,
  level: level,
);

Future<void> controllerSetConfigTunEnabled({
  required BackendTarget target,
  required bool enabled,
}) => RustLib.instance.api.crateBackendApiControlControllerSetConfigTunEnabled(
  target: target,
  enabled: enabled,
);

Future<void> controllerSetConfigBool({
  required BackendTarget target,
  required String key,
  required bool value,
}) => RustLib.instance.api.crateBackendApiControlControllerSetConfigBool(
  target: target,
  key: key,
  value: value,
);

Future<void> controllerSetConfigPort({
  required BackendTarget target,
  required String key,
  required int value,
}) => RustLib.instance.api.crateBackendApiControlControllerSetConfigPort(
  target: target,
  key: key,
  value: value,
);

Future<void> controllerReloadConfigs({
  required BackendTarget target,
  String? path,
  String? payload,
  required bool force,
}) => RustLib.instance.api.crateBackendApiControlControllerReloadConfigs(
  target: target,
  path: path,
  payload: payload,
  force: force,
);

Future<void> controllerUpdateGeo({required BackendTarget target}) => RustLib
    .instance
    .api
    .crateBackendApiControlControllerUpdateGeo(target: target);

Future<void> controllerFlushFakeip({required BackendTarget target}) => RustLib
    .instance
    .api
    .crateBackendApiControlControllerFlushFakeip(target: target);

Future<void> controllerFlushDns({required BackendTarget target}) => RustLib
    .instance
    .api
    .crateBackendApiControlControllerFlushDns(target: target);

Future<String> controllerDnsQuery({
  required BackendTarget target,
  required String name,
  String? qtype,
}) => RustLib.instance.api.crateBackendApiControlControllerDnsQuery(
  target: target,
  name: name,
  qtype: qtype,
);

Future<void> controllerUpgradeCore({
  required BackendTarget target,
  required bool force,
}) => RustLib.instance.api.crateBackendApiControlControllerUpgradeCore(
  target: target,
  force: force,
);

Future<void> controllerUpgradeUi({required BackendTarget target}) => RustLib
    .instance
    .api
    .crateBackendApiControlControllerUpgradeUi(target: target);

Future<void> controllerUpgradeGeo({required BackendTarget target}) => RustLib
    .instance
    .api
    .crateBackendApiControlControllerUpgradeGeo(target: target);

Future<void> controllerRestartCore({required BackendTarget target}) => RustLib
    .instance
    .api
    .crateBackendApiControlControllerRestartCore(target: target);

Future<String> controllerVersion({required BackendTarget target}) => RustLib
    .instance
    .api
    .crateBackendApiControlControllerVersion(target: target);

Future<VersionInfo> controllerVersionInfo({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiControlControllerVersionInfo(
      target: target,
    );
