// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'target.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `bool_value`, `core_config_from_value`, `patch_config_value`, `string_value`, `u32_value`

Future<CoreConfig> configs({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiControlConfigs(target: target);

Future<String> configMode({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiControlConfigMode(target: target);

Future<void> setConfigMode({
  required BackendTarget target,
  required String mode,
}) => RustLib.instance.api.crateBackendApiControlSetConfigMode(
  target: target,
  mode: mode,
);

Future<void> setConfigLogLevel({
  required BackendTarget target,
  required String level,
}) => RustLib.instance.api.crateBackendApiControlSetConfigLogLevel(
  target: target,
  level: level,
);

Future<void> setConfigTunEnabled({
  required BackendTarget target,
  required bool enabled,
}) => RustLib.instance.api.crateBackendApiControlSetConfigTunEnabled(
  target: target,
  enabled: enabled,
);

Future<void> setConfigBool({
  required BackendTarget target,
  required String key,
  required bool value,
}) => RustLib.instance.api.crateBackendApiControlSetConfigBool(
  target: target,
  key: key,
  value: value,
);

Future<void> setConfigPort({
  required BackendTarget target,
  required String key,
  required int value,
}) => RustLib.instance.api.crateBackendApiControlSetConfigPort(
  target: target,
  key: key,
  value: value,
);

Future<void> reloadConfigs({
  required BackendTarget target,
  String? path,
  String? payload,
  required bool force,
}) => RustLib.instance.api.crateBackendApiControlReloadConfigs(
  target: target,
  path: path,
  payload: payload,
  force: force,
);

Future<void> updateGeo({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiControlUpdateGeo(target: target);

Future<void> flushFakeip({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiControlFlushFakeip(target: target);

Future<void> flushDns({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiControlFlushDns(target: target);

Future<String> dnsQuery({
  required BackendTarget target,
  required String name,
  String? qtype,
}) => RustLib.instance.api.crateBackendApiControlDnsQuery(
  target: target,
  name: name,
  qtype: qtype,
);

Future<void> upgradeCore({
  required BackendTarget target,
  required bool force,
}) => RustLib.instance.api.crateBackendApiControlUpgradeCore(
  target: target,
  force: force,
);

Future<void> upgradeUi({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiControlUpgradeUi(target: target);

Future<void> upgradeGeo({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiControlUpgradeGeo(target: target);

Future<void> restartCore({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiControlRestartCore(target: target);

Future<String> version({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiControlVersion(target: target);

Future<VersionInfo> versionInfo({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiControlVersionInfo(target: target);
