// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

CoreSnapshot coreSnapshot() =>
    RustLib.instance.api.crateBackendApiCoreCoreSnapshot();

Future<AppWindow> coreListAppsWindow({
  required String query,
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateBackendApiCoreCoreListAppsWindow(
  query: query,
  offset: offset,
  limit: limit,
);

Future<void> coreUpdateSettings({required CoreConfig config}) =>
    RustLib.instance.api.crateBackendApiCoreCoreUpdateSettings(config: config);

Future<void> coreStart() => RustLib.instance.api.crateBackendApiCoreCoreStart();

Future<void> coreStop() => RustLib.instance.api.crateBackendApiCoreCoreStop();

Stream<CoreSnapshot> coreEvents() =>
    RustLib.instance.api.crateBackendApiCoreCoreEvents();

bool coreSupported() => RustLib.instance.api.crateBackendApiCoreCoreSupported();

Future<List<CoreConfigProfile>> coreConfigList() =>
    RustLib.instance.api.crateBackendApiCoreCoreConfigList();

Future<CoreConfigProfile> coreConfigImport({
  required String url,
  required String text,
  required String name,
  required String userAgent,
}) => RustLib.instance.api.crateBackendApiCoreCoreConfigImport(
  url: url,
  text: text,
  name: name,
  userAgent: userAgent,
);

Future<void> coreConfigSetActive({required String id}) =>
    RustLib.instance.api.crateBackendApiCoreCoreConfigSetActive(id: id);

Future<void> coreConfigEdit({
  required String id,
  required String name,
  required String url,
  required String userAgent,
}) => RustLib.instance.api.crateBackendApiCoreCoreConfigEdit(
  id: id,
  name: name,
  url: url,
  userAgent: userAgent,
);

Future<void> coreConfigUpdate({required String id}) =>
    RustLib.instance.api.crateBackendApiCoreCoreConfigUpdate(id: id);

Future<void> coreConfigDelete({required String id}) =>
    RustLib.instance.api.crateBackendApiCoreCoreConfigDelete(id: id);

class AppInfo {
  final String package;
  final String label;

  const AppInfo({required this.package, required this.label});

  @override
  int get hashCode => package.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppInfo &&
          runtimeType == other.runtimeType &&
          package == other.package &&
          label == other.label;
}

class AppWindow {
  final List<AppInfo> apps;
  final int total;

  const AppWindow({required this.apps, required this.total});

  static Future<AppWindow> default_() =>
      RustLib.instance.api.crateBackendApiCoreAppWindowDefault();

  @override
  int get hashCode => apps.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppWindow &&
          runtimeType == other.runtimeType &&
          apps == other.apps &&
          total == other.total;
}

class CoreConfig {
  final int mixedPort;
  final int port;
  final int socksPort;
  final bool allowLan;
  final String logLevel;
  final TunSettings tun;
  final String externalController;
  final String secret;

  const CoreConfig({
    required this.mixedPort,
    required this.port,
    required this.socksPort,
    required this.allowLan,
    required this.logLevel,
    required this.tun,
    required this.externalController,
    required this.secret,
  });

  static Future<CoreConfig> default_() =>
      RustLib.instance.api.crateBackendApiCoreCoreConfigDefault();

  @override
  int get hashCode =>
      mixedPort.hashCode ^
      port.hashCode ^
      socksPort.hashCode ^
      allowLan.hashCode ^
      logLevel.hashCode ^
      tun.hashCode ^
      externalController.hashCode ^
      secret.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreConfig &&
          runtimeType == other.runtimeType &&
          mixedPort == other.mixedPort &&
          port == other.port &&
          socksPort == other.socksPort &&
          allowLan == other.allowLan &&
          logLevel == other.logLevel &&
          tun == other.tun &&
          externalController == other.externalController &&
          secret == other.secret;
}

/// A kernel config profile (the app only selects among these; the kernel
/// content is never rewritten by the app).
class CoreConfigProfile {
  final String id;
  final String name;
  final CoreProfileKind kind;
  final String sourceUrl;
  final bool active;
  final String userAgent;
  final String etag;

  const CoreConfigProfile({
    required this.id,
    required this.name,
    required this.kind,
    required this.sourceUrl,
    required this.active,
    required this.userAgent,
    required this.etag,
  });

  static Future<CoreConfigProfile> default_() =>
      RustLib.instance.api.crateBackendApiCoreCoreConfigProfileDefault();

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      kind.hashCode ^
      sourceUrl.hashCode ^
      active.hashCode ^
      userAgent.hashCode ^
      etag.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreConfigProfile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          kind == other.kind &&
          sourceUrl == other.sourceUrl &&
          active == other.active &&
          userAgent == other.userAgent &&
          etag == other.etag;
}

enum CoreProfileKind {
  builtin,
  imported;

  static Future<CoreProfileKind> default_() =>
      RustLib.instance.api.crateBackendApiCoreCoreProfileKindDefault();
}

/// Complete Rust-owned state; subscribers may safely skip older snapshots.
class CoreSnapshot {
  final CoreState state;
  final CoreConfig settings;
  final bool tunAttached;
  final bool tunIpv6;
  final String lastError;

  const CoreSnapshot({
    required this.state,
    required this.settings,
    required this.tunAttached,
    required this.tunIpv6,
    required this.lastError,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      settings.hashCode ^
      tunAttached.hashCode ^
      tunIpv6.hashCode ^
      lastError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreSnapshot &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          settings == other.settings &&
          tunAttached == other.tunAttached &&
          tunIpv6 == other.tunIpv6 &&
          lastError == other.lastError;
}

/// Rust-owned local engine lifecycle.
enum CoreState {
  stopped,
  starting,
  running,
  stopping,
  error;

  static Future<CoreState> default_() =>
      RustLib.instance.api.crateBackendApiCoreCoreStateDefault();
}

/// The platform creates the TUN device; the kernel only attaches to its fd.
class TunSettings {
  final bool enabled;

  /// "system" | "gvisor" | "mixed" — kernel stack for the platform fd.
  final String stack;
  final String dns;
  final bool ipv6;
  final int mtu;
  final bool allowBypass;

  /// Bypass mode: "off" (tunnel everything), "lan" (all private subnets),
  /// "custom" (user-provided subnets).
  final String bypassMode;
  final String bypassCustom;
  final bool systemProxy;

  /// VPN access control: "accept_all" | "accept_selected" | "reject_selected".
  final String accessMode;
  final List<String> accessPackages;

  const TunSettings({
    required this.enabled,
    required this.stack,
    required this.dns,
    required this.ipv6,
    required this.mtu,
    required this.allowBypass,
    required this.bypassMode,
    required this.bypassCustom,
    required this.systemProxy,
    required this.accessMode,
    required this.accessPackages,
  });

  static Future<TunSettings> default_() =>
      RustLib.instance.api.crateBackendApiCoreTunSettingsDefault();

  @override
  int get hashCode =>
      enabled.hashCode ^
      stack.hashCode ^
      dns.hashCode ^
      ipv6.hashCode ^
      mtu.hashCode ^
      allowBypass.hashCode ^
      bypassMode.hashCode ^
      bypassCustom.hashCode ^
      systemProxy.hashCode ^
      accessMode.hashCode ^
      accessPackages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TunSettings &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          stack == other.stack &&
          dns == other.dns &&
          ipv6 == other.ipv6 &&
          mtu == other.mtu &&
          allowBypass == other.allowBypass &&
          bypassMode == other.bypassMode &&
          bypassCustom == other.bypassCustom &&
          systemProxy == other.systemProxy &&
          accessMode == other.accessMode &&
          accessPackages == other.accessPackages;
}
