// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'target.dart';

// These functions are ignored because they are not marked as `pub`: `unsupported`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

Future<List<OutboundEntry>> diagnosticsOutbounds({
  required BackendTarget target,
}) => RustLib.instance.api.crateBackendApiDiagnosticsDiagnosticsOutbounds(
  target: target,
);

Stream<NetworkQualityProgress> networkQualityTestStream({
  required BackendTarget target,
  required String configUrl,
  required String outboundTag,
  required bool serial,
  required int maxRuntimeSeconds,
  required bool http3,
}) => RustLib.instance.api.crateBackendApiDiagnosticsNetworkQualityTestStream(
  target: target,
  configUrl: configUrl,
  outboundTag: outboundTag,
  serial: serial,
  maxRuntimeSeconds: maxRuntimeSeconds,
  http3: http3,
);

Stream<StunTestProgress> stunTestStream({
  required BackendTarget target,
  required String server,
  required String outboundTag,
}) => RustLib.instance.api.crateBackendApiDiagnosticsStunTestStream(
  target: target,
  server: server,
  outboundTag: outboundTag,
);

class NetworkQualityProgress {
  final int phase;
  final PlatformInt64 downloadCapacity;
  final PlatformInt64 uploadCapacity;
  final int downloadRpm;
  final int uploadRpm;
  final int idleLatencyMs;
  final PlatformInt64 elapsedMs;
  final bool isFinal;
  final String error;
  final int downloadCapacityAccuracy;
  final int uploadCapacityAccuracy;
  final int downloadRpmAccuracy;
  final int uploadRpmAccuracy;

  const NetworkQualityProgress({
    required this.phase,
    required this.downloadCapacity,
    required this.uploadCapacity,
    required this.downloadRpm,
    required this.uploadRpm,
    required this.idleLatencyMs,
    required this.elapsedMs,
    required this.isFinal,
    required this.error,
    required this.downloadCapacityAccuracy,
    required this.uploadCapacityAccuracy,
    required this.downloadRpmAccuracy,
    required this.uploadRpmAccuracy,
  });

  static Future<NetworkQualityProgress> default_() => RustLib.instance.api
      .crateBackendApiDiagnosticsNetworkQualityProgressDefault();

  @override
  int get hashCode =>
      phase.hashCode ^
      downloadCapacity.hashCode ^
      uploadCapacity.hashCode ^
      downloadRpm.hashCode ^
      uploadRpm.hashCode ^
      idleLatencyMs.hashCode ^
      elapsedMs.hashCode ^
      isFinal.hashCode ^
      error.hashCode ^
      downloadCapacityAccuracy.hashCode ^
      uploadCapacityAccuracy.hashCode ^
      downloadRpmAccuracy.hashCode ^
      uploadRpmAccuracy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkQualityProgress &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          downloadCapacity == other.downloadCapacity &&
          uploadCapacity == other.uploadCapacity &&
          downloadRpm == other.downloadRpm &&
          uploadRpm == other.uploadRpm &&
          idleLatencyMs == other.idleLatencyMs &&
          elapsedMs == other.elapsedMs &&
          isFinal == other.isFinal &&
          error == other.error &&
          downloadCapacityAccuracy == other.downloadCapacityAccuracy &&
          uploadCapacityAccuracy == other.uploadCapacityAccuracy &&
          downloadRpmAccuracy == other.downloadRpmAccuracy &&
          uploadRpmAccuracy == other.uploadRpmAccuracy;
}

class OutboundEntry {
  final String tag;
  final String outboundType;

  const OutboundEntry({required this.tag, required this.outboundType});

  static Future<OutboundEntry> default_() =>
      RustLib.instance.api.crateBackendApiDiagnosticsOutboundEntryDefault();

  @override
  int get hashCode => tag.hashCode ^ outboundType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutboundEntry &&
          runtimeType == other.runtimeType &&
          tag == other.tag &&
          outboundType == other.outboundType;
}

class StunTestProgress {
  final int phase;
  final String externalAddr;
  final int latencyMs;
  final int natMapping;
  final int natFiltering;
  final bool isFinal;
  final String error;
  final bool natTypeSupported;

  const StunTestProgress({
    required this.phase,
    required this.externalAddr,
    required this.latencyMs,
    required this.natMapping,
    required this.natFiltering,
    required this.isFinal,
    required this.error,
    required this.natTypeSupported,
  });

  static Future<StunTestProgress> default_() =>
      RustLib.instance.api.crateBackendApiDiagnosticsStunTestProgressDefault();

  @override
  int get hashCode =>
      phase.hashCode ^
      externalAddr.hashCode ^
      latencyMs.hashCode ^
      natMapping.hashCode ^
      natFiltering.hashCode ^
      isFinal.hashCode ^
      error.hashCode ^
      natTypeSupported.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StunTestProgress &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          externalAddr == other.externalAddr &&
          latencyMs == other.latencyMs &&
          natMapping == other.natMapping &&
          natFiltering == other.natFiltering &&
          isFinal == other.isFinal &&
          error == other.error &&
          natTypeSupported == other.natTypeSupported;
}
