// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../utils/error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// On-demand diagnostics. App process totals include the embedded Go runtime.
Future<MemoryDetails> memoryDetails({required bool includeKernel}) => RustLib
    .instance
    .api
    .crateBackendApiMemoryMemoryDetails(includeKernel: includeKernel);

class AppMemoryInfo {
  final BigInt pss;
  final BigInt privateDirty;
  final BigInt privateClean;
  final BigInt sharedDirty;
  final BigInt sharedClean;
  final BigInt? rss;
  final BigInt? peakRss;
  final BigInt? virtualSize;
  final BigInt? swapPss;
  final BigInt? javaHeap;
  final BigInt? nativeHeap;
  final BigInt? graphics;
  final BigInt? code;
  final BigInt? stack;
  final BigInt? privateOther;
  final BigInt? system;
  final BigInt javaAllocated;
  final BigInt javaCapacity;
  final BigInt javaLimit;
  final BigInt nativeAllocated;
  final BigInt nativeCapacity;
  final BigInt nativeFree;

  const AppMemoryInfo({
    required this.pss,
    required this.privateDirty,
    required this.privateClean,
    required this.sharedDirty,
    required this.sharedClean,
    this.rss,
    this.peakRss,
    this.virtualSize,
    this.swapPss,
    this.javaHeap,
    this.nativeHeap,
    this.graphics,
    this.code,
    this.stack,
    this.privateOther,
    this.system,
    required this.javaAllocated,
    required this.javaCapacity,
    required this.javaLimit,
    required this.nativeAllocated,
    required this.nativeCapacity,
    required this.nativeFree,
  });

  @override
  int get hashCode =>
      pss.hashCode ^
      privateDirty.hashCode ^
      privateClean.hashCode ^
      sharedDirty.hashCode ^
      sharedClean.hashCode ^
      rss.hashCode ^
      peakRss.hashCode ^
      virtualSize.hashCode ^
      swapPss.hashCode ^
      javaHeap.hashCode ^
      nativeHeap.hashCode ^
      graphics.hashCode ^
      code.hashCode ^
      stack.hashCode ^
      privateOther.hashCode ^
      system.hashCode ^
      javaAllocated.hashCode ^
      javaCapacity.hashCode ^
      javaLimit.hashCode ^
      nativeAllocated.hashCode ^
      nativeCapacity.hashCode ^
      nativeFree.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppMemoryInfo &&
          runtimeType == other.runtimeType &&
          pss == other.pss &&
          privateDirty == other.privateDirty &&
          privateClean == other.privateClean &&
          sharedDirty == other.sharedDirty &&
          sharedClean == other.sharedClean &&
          rss == other.rss &&
          peakRss == other.peakRss &&
          virtualSize == other.virtualSize &&
          swapPss == other.swapPss &&
          javaHeap == other.javaHeap &&
          nativeHeap == other.nativeHeap &&
          graphics == other.graphics &&
          code == other.code &&
          stack == other.stack &&
          privateOther == other.privateOther &&
          system == other.system &&
          javaAllocated == other.javaAllocated &&
          javaCapacity == other.javaCapacity &&
          javaLimit == other.javaLimit &&
          nativeAllocated == other.nativeAllocated &&
          nativeCapacity == other.nativeCapacity &&
          nativeFree == other.nativeFree;
}

class KernelMemoryInfo {
  final BigInt heapAlloc;
  final BigInt heapInuse;
  final BigInt heapIdle;
  final BigInt heapReleased;
  final BigInt stackInuse;
  final BigInt sys;
  final int gcCount;
  final int goroutines;

  const KernelMemoryInfo({
    required this.heapAlloc,
    required this.heapInuse,
    required this.heapIdle,
    required this.heapReleased,
    required this.stackInuse,
    required this.sys,
    required this.gcCount,
    required this.goroutines,
  });

  @override
  int get hashCode =>
      heapAlloc.hashCode ^
      heapInuse.hashCode ^
      heapIdle.hashCode ^
      heapReleased.hashCode ^
      stackInuse.hashCode ^
      sys.hashCode ^
      gcCount.hashCode ^
      goroutines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KernelMemoryInfo &&
          runtimeType == other.runtimeType &&
          heapAlloc == other.heapAlloc &&
          heapInuse == other.heapInuse &&
          heapIdle == other.heapIdle &&
          heapReleased == other.heapReleased &&
          stackInuse == other.stackInuse &&
          sys == other.sys &&
          gcCount == other.gcCount &&
          goroutines == other.goroutines;
}

class MemoryDetails {
  final AppMemoryInfo? app;
  final KernelMemoryInfo? kernel;
  final String? appError;
  final String? kernelError;

  const MemoryDetails({this.app, this.kernel, this.appError, this.kernelError});

  static Future<MemoryDetails> default_() =>
      RustLib.instance.api.crateBackendApiMemoryMemoryDetailsDefault();

  @override
  int get hashCode =>
      app.hashCode ^ kernel.hashCode ^ appError.hashCode ^ kernelError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoryDetails &&
          runtimeType == other.runtimeType &&
          app == other.app &&
          kernel == other.kernel &&
          appError == other.appError &&
          kernelError == other.kernelError;
}
