// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'target.dart';
import 'types.dart';

Future<String> controllerProxyProviders({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiProvidersControllerProxyProviders(
      target: target,
    );

Future<List<ProxyProviderEntry>> controllerProxyProviderCatalog({
  required BackendTarget target,
}) => RustLib.instance.api
    .crateBackendApiProvidersControllerProxyProviderCatalog(target: target);

Future<void> controllerProxyProviderUpdate({
  required BackendTarget target,
  required String name,
}) =>
    RustLib.instance.api.crateBackendApiProvidersControllerProxyProviderUpdate(
      target: target,
      name: name,
    );

Future<void> controllerProxyProviderHealthcheck({
  required BackendTarget target,
  required String name,
}) => RustLib.instance.api
    .crateBackendApiProvidersControllerProxyProviderHealthcheck(
      target: target,
      name: name,
    );

Future<String> controllerRuleProviders({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiProvidersControllerRuleProviders(
      target: target,
    );

Future<List<RuleProviderEntry>> controllerRuleProviderCatalog({
  required BackendTarget target,
}) => RustLib.instance.api
    .crateBackendApiProvidersControllerRuleProviderCatalog(target: target);

Future<void> controllerRuleProviderUpdate({
  required BackendTarget target,
  required String name,
}) => RustLib.instance.api.crateBackendApiProvidersControllerRuleProviderUpdate(
  target: target,
  name: name,
);

Future<String> controllerStorageGet({
  required BackendTarget target,
  required String key,
}) => RustLib.instance.api.crateBackendApiProvidersControllerStorageGet(
  target: target,
  key: key,
);

Future<void> controllerStorageSet({
  required BackendTarget target,
  required String key,
  required String value,
}) => RustLib.instance.api.crateBackendApiProvidersControllerStorageSet(
  target: target,
  key: key,
  value: value,
);

Future<void> controllerStorageDelete({
  required BackendTarget target,
  required String key,
}) => RustLib.instance.api.crateBackendApiProvidersControllerStorageDelete(
  target: target,
  key: key,
);
