// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'target.dart';
import 'types.dart';

Future<String> proxyProviders({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiProvidersProxyProviders(target: target);

Future<List<ProxyProviderEntry>> proxyProviderCatalog({
  required BackendTarget target,
}) => RustLib.instance.api.crateBackendApiProvidersProxyProviderCatalog(
  target: target,
);

Future<void> proxyProviderUpdate({
  required BackendTarget target,
  required String name,
}) => RustLib.instance.api.crateBackendApiProvidersProxyProviderUpdate(
  target: target,
  name: name,
);

Future<void> proxyProviderHealthcheck({
  required BackendTarget target,
  required String name,
}) => RustLib.instance.api.crateBackendApiProvidersProxyProviderHealthcheck(
  target: target,
  name: name,
);

Future<String> ruleProviders({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiProvidersRuleProviders(target: target);

Future<List<RuleProviderEntry>> ruleProviderCatalog({
  required BackendTarget target,
}) => RustLib.instance.api.crateBackendApiProvidersRuleProviderCatalog(
  target: target,
);

Future<void> ruleProviderUpdate({
  required BackendTarget target,
  required String name,
}) => RustLib.instance.api.crateBackendApiProvidersRuleProviderUpdate(
  target: target,
  name: name,
);

Future<String> storageGet({
  required BackendTarget target,
  required String key,
}) => RustLib.instance.api.crateBackendApiProvidersStorageGet(
  target: target,
  key: key,
);

Future<void> storageSet({
  required BackendTarget target,
  required String key,
  required String value,
}) => RustLib.instance.api.crateBackendApiProvidersStorageSet(
  target: target,
  key: key,
  value: value,
);

Future<void> storageDelete({
  required BackendTarget target,
  required String key,
}) => RustLib.instance.api.crateBackendApiProvidersStorageDelete(
  target: target,
  key: key,
);
