// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'target.dart';
import 'types.dart';

Future<List<GroupDelayEntry>> groupDelay({
  required BackendTarget target,
  required String group,
  required String testUrl,
  required int timeoutMs,
  String? expectedStatus,
  int? concurrency,
}) => RustLib.instance.api.crateBackendApiProxyDelayGroupDelay(
  target: target,
  group: group,
  testUrl: testUrl,
  timeoutMs: timeoutMs,
  expectedStatus: expectedStatus,
  concurrency: concurrency,
);

Future<PlatformInt64> proxyDelay({
  required BackendTarget target,
  required String name,
  required String testUrl,
  required int timeoutMs,
  String? expectedStatus,
}) => RustLib.instance.api.crateBackendApiProxyDelayProxyDelay(
  target: target,
  name: name,
  testUrl: testUrl,
  timeoutMs: timeoutMs,
  expectedStatus: expectedStatus,
);

Future<List<ProxyDelayEntry>> proxyBatchDelay({
  required BackendTarget target,
  required List<String> names,
  required String testUrl,
  required int timeoutMs,
  String? expectedStatus,
  required int concurrency,
}) => RustLib.instance.api.crateBackendApiProxyDelayProxyBatchDelay(
  target: target,
  names: names,
  testUrl: testUrl,
  timeoutMs: timeoutMs,
  expectedStatus: expectedStatus,
  concurrency: concurrency,
);

Future<List<ProxyDelayEntry>> proxyGroupBatchDelay({
  required BackendTarget target,
  required String group,
  required String testUrl,
  required int timeoutMs,
  String? expectedStatus,
  required int concurrency,
}) => RustLib.instance.api.crateBackendApiProxyDelayProxyGroupBatchDelay(
  target: target,
  group: group,
  testUrl: testUrl,
  timeoutMs: timeoutMs,
  expectedStatus: expectedStatus,
  concurrency: concurrency,
);

Stream<ProxyDelayEvent> proxyGroupDelayStream({
  required BackendTarget target,
  required String group,
  required String testUrl,
  required int timeoutMs,
  String? expectedStatus,
  required int concurrency,
  required ProxyMemberSort memberSort,
  required int windowOffset,
  required int windowLimit,
  required int windowMembersHash,
}) => RustLib.instance.api.crateBackendApiProxyDelayProxyGroupDelayStream(
  target: target,
  group: group,
  testUrl: testUrl,
  timeoutMs: timeoutMs,
  expectedStatus: expectedStatus,
  concurrency: concurrency,
  memberSort: memberSort,
  windowOffset: windowOffset,
  windowLimit: windowLimit,
  windowMembersHash: windowMembersHash,
);

Future<ProxyDelayEvent> proxyDelayWindow({
  required BackendTarget target,
  required String group,
  required String name,
  required String testUrl,
  required int timeoutMs,
  String? expectedStatus,
  required ProxyMemberSort memberSort,
  required int windowOffset,
  required int windowLimit,
  required int windowMembersHash,
}) => RustLib.instance.api.crateBackendApiProxyDelayProxyDelayWindow(
  target: target,
  group: group,
  name: name,
  testUrl: testUrl,
  timeoutMs: timeoutMs,
  expectedStatus: expectedStatus,
  memberSort: memberSort,
  windowOffset: windowOffset,
  windowLimit: windowLimit,
  windowMembersHash: windowMembersHash,
);
