// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'target.dart';
import 'types.dart';

Future<String> groups({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiProxiesGroups(target: target);

Future<String> proxies({
  required BackendTarget target,
  String? namePattern,
  String? typePattern,
  required bool groupsOnly,
}) => RustLib.instance.api.crateBackendApiProxiesProxies(
  target: target,
  namePattern: namePattern,
  typePattern: typePattern,
  groupsOnly: groupsOnly,
);

Future<String> proxyDetail({
  required BackendTarget target,
  required String name,
}) => RustLib.instance.api.crateBackendApiProxiesProxyDetail(
  target: target,
  name: name,
);

Future<void> selectProxy({
  required BackendTarget target,
  required String group,
  required String name,
}) => RustLib.instance.api.crateBackendApiProxiesSelectProxy(
  target: target,
  group: group,
  name: name,
);

Future<void> unfixProxy({
  required BackendTarget target,
  required String name,
}) => RustLib.instance.api.crateBackendApiProxiesUnfixProxy(
  target: target,
  name: name,
);

Future<ProxyCatalog> proxyCatalog({
  required BackendTarget target,
  required bool includeHidden,
  required String filter,
}) => RustLib.instance.api.crateBackendApiProxiesProxyCatalog(
  target: target,
  includeHidden: includeHidden,
  filter: filter,
);

Future<List<ProxyMemberEntry>> proxyGroupMembers({
  required BackendTarget target,
  required String group,
  required int offset,
  required int limit,
  required ProxyMemberSort memberSort,
}) => RustLib.instance.api.crateBackendApiProxiesProxyGroupMembers(
  target: target,
  group: group,
  offset: offset,
  limit: limit,
  memberSort: memberSort,
);
