// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../utils/error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'target.dart';
import 'types.dart';

Future<List<GroupDelayEntry>> controllerGroupDelay({
  required BackendTarget target,
  required String group,
  required String testUrl,
  required int timeoutMs,
  String? expectedStatus,
  int? concurrency,
}) => RustLib.instance.api.crateBackendApiProxyDelayControllerGroupDelay(
  target: target,
  group: group,
  testUrl: testUrl,
  timeoutMs: timeoutMs,
  expectedStatus: expectedStatus,
  concurrency: concurrency,
);

Future<PlatformInt64> controllerProxyDelay({
  required BackendTarget target,
  required String name,
  required String testUrl,
  required int timeoutMs,
  String? expectedStatus,
}) => RustLib.instance.api.crateBackendApiProxyDelayControllerProxyDelay(
  target: target,
  name: name,
  testUrl: testUrl,
  timeoutMs: timeoutMs,
  expectedStatus: expectedStatus,
);

Future<List<ProxyDelayEntry>> controllerProxyBatchDelay({
  required BackendTarget target,
  required List<String> names,
  required String testUrl,
  required int timeoutMs,
  String? expectedStatus,
  required int concurrency,
}) => RustLib.instance.api.crateBackendApiProxyDelayControllerProxyBatchDelay(
  target: target,
  names: names,
  testUrl: testUrl,
  timeoutMs: timeoutMs,
  expectedStatus: expectedStatus,
  concurrency: concurrency,
);

Future<List<ProxyDelayEntry>> controllerProxyGroupBatchDelay({
  required BackendTarget target,
  required String group,
  required String testUrl,
  required int timeoutMs,
  String? expectedStatus,
  required int concurrency,
}) => RustLib.instance.api
    .crateBackendApiProxyDelayControllerProxyGroupBatchDelay(
      target: target,
      group: group,
      testUrl: testUrl,
      timeoutMs: timeoutMs,
      expectedStatus: expectedStatus,
      concurrency: concurrency,
    );

Stream<ProxyDelayEvent> controllerProxyGroupDelayStream({
  required BackendTarget target,
  required String group,
  required String testUrl,
  required int timeoutMs,
  String? expectedStatus,
  required int concurrency,
  required ProxyMemberSort memberSort,
  required int windowOffset,
  required int windowLimit,
  required int windowMembersHash,
}) => RustLib.instance.api
    .crateBackendApiProxyDelayControllerProxyGroupDelayStream(
      target: target,
      group: group,
      testUrl: testUrl,
      timeoutMs: timeoutMs,
      expectedStatus: expectedStatus,
      concurrency: concurrency,
      memberSort: memberSort,
      windowOffset: windowOffset,
      windowLimit: windowLimit,
      windowMembersHash: windowMembersHash,
    );

Future<ProxyDelayEvent> controllerProxyDelayWindow({
  required BackendTarget target,
  required String group,
  required String name,
  required String testUrl,
  required int timeoutMs,
  String? expectedStatus,
  required ProxyMemberSort memberSort,
  required int windowOffset,
  required int windowLimit,
  required int windowMembersHash,
}) => RustLib.instance.api.crateBackendApiProxyDelayControllerProxyDelayWindow(
  target: target,
  group: group,
  name: name,
  testUrl: testUrl,
  timeoutMs: timeoutMs,
  expectedStatus: expectedStatus,
  memberSort: memberSort,
  windowOffset: windowOffset,
  windowLimit: windowLimit,
  windowMembersHash: windowMembersHash,
);
