// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'target.dart';
import 'types.dart';

Future<String> controllerGroups({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiProxiesControllerGroups(target: target);

Future<String> controllerProxies({
  required BackendTarget target,
  String? namePattern,
  String? typePattern,
  required bool groupsOnly,
}) => RustLib.instance.api.crateBackendApiProxiesControllerProxies(
  target: target,
  namePattern: namePattern,
  typePattern: typePattern,
  groupsOnly: groupsOnly,
);

Future<String> controllerProxyDetail({
  required BackendTarget target,
  required String name,
}) => RustLib.instance.api.crateBackendApiProxiesControllerProxyDetail(
  target: target,
  name: name,
);

Future<void> controllerSelectProxy({
  required BackendTarget target,
  required String group,
  required String name,
}) => RustLib.instance.api.crateBackendApiProxiesControllerSelectProxy(
  target: target,
  group: group,
  name: name,
);

Future<void> controllerUnfixProxy({
  required BackendTarget target,
  required String name,
}) => RustLib.instance.api.crateBackendApiProxiesControllerUnfixProxy(
  target: target,
  name: name,
);

Future<ProxyCatalog> controllerProxyCatalog({
  required BackendTarget target,
  required bool includeHidden,
  required bool resolveProviderCurrentDelay,
  required String filter,
}) => RustLib.instance.api.crateBackendApiProxiesControllerProxyCatalog(
  target: target,
  includeHidden: includeHidden,
  resolveProviderCurrentDelay: resolveProviderCurrentDelay,
  filter: filter,
);

Future<List<ProxyMemberEntry>> controllerProxyGroupMembers({
  required BackendTarget target,
  required String group,
  required int offset,
  required int limit,
  required ProxyMemberSort memberSort,
}) => RustLib.instance.api.crateBackendApiProxiesControllerProxyGroupMembers(
  target: target,
  group: group,
  offset: offset,
  limit: limit,
  memberSort: memberSort,
);
