// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../utils/error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initCache({
  required String cacheDir,
  required bool allowInsecureOnlineResources,
}) => RustLib.instance.api.crateBackendApiResourcesInitCache(
  cacheDir: cacheDir,
  allowInsecureOnlineResources: allowInsecureOnlineResources,
);

Future<void> setOnlineResourceAllowInsecure({required bool allowInsecure}) =>
    RustLib.instance.api.crateBackendApiResourcesSetOnlineResourceAllowInsecure(
      allowInsecure: allowInsecure,
    );

Future<Uint8List> fetchIcon({required String url}) =>
    RustLib.instance.api.crateBackendApiResourcesFetchIcon(url: url);

Future<Uint8List?> fetchProcessIcon({required String path, int? size}) =>
    RustLib.instance.api.crateBackendApiResourcesFetchProcessIcon(
      path: path,
      size: size,
    );

Future<Uint8List?> cachedProcessIcon({required String key, int? size}) =>
    RustLib.instance.api.crateBackendApiResourcesCachedProcessIcon(
      key: key,
      size: size,
    );

Future<void> storeProcessIcon({
  required String key,
  required List<int> bytes,
}) => RustLib.instance.api.crateBackendApiResourcesStoreProcessIcon(
  key: key,
  bytes: bytes,
);

Future<String?> fetchProcessName({required String path}) =>
    RustLib.instance.api.crateBackendApiResourcesFetchProcessName(path: path);

Future<String?> cachedProcessName({required String key}) =>
    RustLib.instance.api.crateBackendApiResourcesCachedProcessName(key: key);

Future<void> storeProcessName({required String key, required String name}) =>
    RustLib.instance.api.crateBackendApiResourcesStoreProcessName(
      key: key,
      name: name,
    );

Future<void> resetProcessIconMisses() =>
    RustLib.instance.api.crateBackendApiResourcesResetProcessIconMisses();

Future<BigInt> iconCacheSize() =>
    RustLib.instance.api.crateBackendApiResourcesIconCacheSize();

Future<void> clearIconCache() =>
    RustLib.instance.api.crateBackendApiResourcesClearIconCache();

Future<List<String>> systemFontFamilies() =>
    RustLib.instance.api.crateBackendApiResourcesSystemFontFamilies();
