// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'target.dart';
import 'types.dart';

Future<int> rulesCount({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiRulesRulesCount(target: target);

Future<RulesSummary> rulesLoad({
  required BackendTarget target,
  required String filter,
}) => RustLib.instance.api.crateBackendApiRulesRulesLoad(
  target: target,
  filter: filter,
);

Future<RulesSummary> rulesSetFilter({
  required BackendTarget target,
  required String filter,
}) => RustLib.instance.api.crateBackendApiRulesRulesSetFilter(
  target: target,
  filter: filter,
);

Future<List<RuleEntry>> rulesWindow({
  required BackendTarget target,
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateBackendApiRulesRulesWindow(
  target: target,
  offset: offset,
  limit: limit,
);

Future<void> rulesDisable({
  required BackendTarget target,
  required int index,
  required bool disabled,
}) => RustLib.instance.api.crateBackendApiRulesRulesDisable(
  target: target,
  index: index,
  disabled: disabled,
);
