// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'target.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `apply_runtime`, `apply`, `boxed_non_empty`, `cache`, `entry`, `filtered_len`, `intern`, `new`, `new`, `release_target`, `rule_matches`, `same_shape`, `set_filter`, `string_at`, `summary`, `to_entry`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CachedRuleEntry`, `RuleStringInterner`, `RulesCache`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<RulesSummary> controllerRulesLoad({
  required BackendTarget target,
  required String filter,
  required bool force,
}) => RustLib.instance.api.crateBackendApiRulesControllerRulesLoad(
  target: target,
  filter: filter,
  force: force,
);

Future<RulesSummary> controllerRulesSetFilter({
  required BackendTarget target,
  required String filter,
}) => RustLib.instance.api.crateBackendApiRulesControllerRulesSetFilter(
  target: target,
  filter: filter,
);

Future<List<RuleEntry>> controllerRulesWindow({
  required BackendTarget target,
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateBackendApiRulesControllerRulesWindow(
  target: target,
  offset: offset,
  limit: limit,
);

Future<void> controllerRulesDisable({
  required BackendTarget target,
  required int index,
  required bool disabled,
}) => RustLib.instance.api.crateBackendApiRulesControllerRulesDisable(
  target: target,
  index: index,
  disabled: disabled,
);
