// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'target.dart';
import 'types.dart';

Future<int> controllerRulesCount({required BackendTarget target}) => RustLib
    .instance
    .api
    .crateBackendApiRulesControllerRulesCount(target: target);

Future<RulesSummary> controllerRulesLoad({
  required BackendTarget target,
  required String filter,
}) => RustLib.instance.api.crateBackendApiRulesControllerRulesLoad(
  target: target,
  filter: filter,
);

Future<RulesSummary> controllerRulesSetFilter({
  required BackendTarget target,
  required String filter,
}) => RustLib.instance.api.crateBackendApiRulesControllerRulesSetFilter(
  target: target,
  filter: filter,
);

Future<List<RuleEntry>> controllerRulesWindow({
  required BackendTarget target,
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateBackendApiRulesControllerRulesWindow(
  target: target,
  offset: offset,
  limit: limit,
);

Future<void> controllerRulesDisable({
  required BackendTarget target,
  required int index,
  required bool disabled,
}) => RustLib.instance.api.crateBackendApiRulesControllerRulesDisable(
  target: target,
  index: index,
  disabled: disabled,
);
