// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'target.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `configs_cache`, `configs`, `diagnostics_cache`, `diagnostics_outbounds`, `invalidate_configs`, `release_target`

/// Fetch the immutable/low-frequency data for one controller as soon as it is
/// connected. Each getter below shares the same in-flight load, so a page that
/// opens during bootstrap waits for that request instead of starting another.
Future<SessionBootstrap> controllerPrepareTarget({
  required BackendTarget target,
}) => RustLib.instance.api.crateBackendApiSessionControllerPrepareTarget(
  target: target,
);
