// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../utils/error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'target.dart';
import 'types.dart';

Stream<TrafficSample> controllerTrafficStream({
  required BackendTarget target,
}) => RustLib.instance.api.crateBackendApiStreamsControllerTrafficStream(
  target: target,
);

Stream<MemorySample> controllerMemoryStream({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiStreamsControllerMemoryStream(
      target: target,
    );

Stream<LogsFrame> controllerLogsStream({
  required BackendTarget target,
  required int infoCapacity,
}) => RustLib.instance.api.crateBackendApiStreamsControllerLogsStream(
  target: target,
  infoCapacity: infoCapacity,
);

Future<LogWindow> controllerFetchLogsWindow({
  required BackendTarget target,
  required String level,
  required String query,
  required int offset,
  required int limit,
  required bool fromEnd,
  required BigInt anchorId,
}) => RustLib.instance.api.crateBackendApiStreamsControllerFetchLogsWindow(
  target: target,
  level: level,
  query: query,
  offset: offset,
  limit: limit,
  fromEnd: fromEnd,
  anchorId: anchorId,
);

Future<void> controllerClearLogs({required BackendTarget target}) => RustLib
    .instance
    .api
    .crateBackendApiStreamsControllerClearLogs(target: target);
