// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'target.dart';
import 'types.dart';

Stream<TrafficSample> trafficStream({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiStreamsTrafficStream(target: target);

Stream<MemorySample> memoryStream({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiStreamsMemoryStream(target: target);

Stream<List<LogEntry>> logsStream({
  required BackendTarget target,
  required int infoCapacity,
}) => RustLib.instance.api.crateBackendApiStreamsLogsStream(
  target: target,
  infoCapacity: infoCapacity,
);

Future<void> clearLogs({required BackendTarget target}) =>
    RustLib.instance.api.crateBackendApiStreamsClearLogs(target: target);
