// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../utils/error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'target.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Stream<TailscalePingUpdate> tailscalePingStream({
  required BackendTarget target,
  required String endpointTag,
  required String peerIp,
}) => RustLib.instance.api.crateBackendApiTailscaleTailscalePingStream(
  target: target,
  endpointTag: endpointTag,
  peerIp: peerIp,
);

Stream<TailscaleStatus> tailscaleStatusStream({
  required BackendTarget target,
}) => RustLib.instance.api.crateBackendApiTailscaleTailscaleStatusStream(
  target: target,
);

Future<void> tailscaleLogout({
  required BackendTarget target,
  required String endpointTag,
}) => RustLib.instance.api.crateBackendApiTailscaleTailscaleLogout(
  target: target,
  endpointTag: endpointTag,
);

Future<void> tailscaleSetExitNode({
  required BackendTarget target,
  required String endpointTag,
  required String stableId,
}) => RustLib.instance.api.crateBackendApiTailscaleTailscaleSetExitNode(
  target: target,
  endpointTag: endpointTag,
  stableId: stableId,
);

class TailscaleEndpointStatus {
  final String endpointTag;
  final String backendState;
  final String authUrl;
  final String networkName;
  final String magicDnsSuffix;
  final TailscalePeer? selfPeer;
  final List<TailscaleUserGroup> userGroups;
  final TailscalePeer? exitNode;
  final bool keyAuth;

  const TailscaleEndpointStatus({
    required this.endpointTag,
    required this.backendState,
    required this.authUrl,
    required this.networkName,
    required this.magicDnsSuffix,
    this.selfPeer,
    required this.userGroups,
    this.exitNode,
    required this.keyAuth,
  });

  static Future<TailscaleEndpointStatus> default_() => RustLib.instance.api
      .crateBackendApiTailscaleTailscaleEndpointStatusDefault();

  @override
  int get hashCode =>
      endpointTag.hashCode ^
      backendState.hashCode ^
      authUrl.hashCode ^
      networkName.hashCode ^
      magicDnsSuffix.hashCode ^
      selfPeer.hashCode ^
      userGroups.hashCode ^
      exitNode.hashCode ^
      keyAuth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TailscaleEndpointStatus &&
          runtimeType == other.runtimeType &&
          endpointTag == other.endpointTag &&
          backendState == other.backendState &&
          authUrl == other.authUrl &&
          networkName == other.networkName &&
          magicDnsSuffix == other.magicDnsSuffix &&
          selfPeer == other.selfPeer &&
          userGroups == other.userGroups &&
          exitNode == other.exitNode &&
          keyAuth == other.keyAuth;
}

class TailscalePeer {
  final String stableId;
  final String hostName;
  final String dnsName;
  final String os;
  final List<String> tailscaleIps;
  final bool online;
  final bool exitNode;
  final bool exitNodeOption;
  final bool active;
  final PlatformInt64 rxBytes;
  final PlatformInt64 txBytes;
  final PlatformInt64 keyExpiry;
  final bool expired;
  final List<String> sshHostKeys;
  final bool shareeNode;
  final PlatformInt64 lastSeen;

  const TailscalePeer({
    required this.stableId,
    required this.hostName,
    required this.dnsName,
    required this.os,
    required this.tailscaleIps,
    required this.online,
    required this.exitNode,
    required this.exitNodeOption,
    required this.active,
    required this.rxBytes,
    required this.txBytes,
    required this.keyExpiry,
    required this.expired,
    required this.sshHostKeys,
    required this.shareeNode,
    required this.lastSeen,
  });

  static Future<TailscalePeer> default_() =>
      RustLib.instance.api.crateBackendApiTailscaleTailscalePeerDefault();

  @override
  int get hashCode =>
      stableId.hashCode ^
      hostName.hashCode ^
      dnsName.hashCode ^
      os.hashCode ^
      tailscaleIps.hashCode ^
      online.hashCode ^
      exitNode.hashCode ^
      exitNodeOption.hashCode ^
      active.hashCode ^
      rxBytes.hashCode ^
      txBytes.hashCode ^
      keyExpiry.hashCode ^
      expired.hashCode ^
      sshHostKeys.hashCode ^
      shareeNode.hashCode ^
      lastSeen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TailscalePeer &&
          runtimeType == other.runtimeType &&
          stableId == other.stableId &&
          hostName == other.hostName &&
          dnsName == other.dnsName &&
          os == other.os &&
          tailscaleIps == other.tailscaleIps &&
          online == other.online &&
          exitNode == other.exitNode &&
          exitNodeOption == other.exitNodeOption &&
          active == other.active &&
          rxBytes == other.rxBytes &&
          txBytes == other.txBytes &&
          keyExpiry == other.keyExpiry &&
          expired == other.expired &&
          sshHostKeys == other.sshHostKeys &&
          shareeNode == other.shareeNode &&
          lastSeen == other.lastSeen;
}

class TailscalePingUpdate {
  final double latencyMs;
  final bool isDirect;
  final String endpoint;
  final int derpRegionId;
  final String derpRegionCode;
  final String error;

  const TailscalePingUpdate({
    required this.latencyMs,
    required this.isDirect,
    required this.endpoint,
    required this.derpRegionId,
    required this.derpRegionCode,
    required this.error,
  });

  static Future<TailscalePingUpdate> default_() =>
      RustLib.instance.api.crateBackendApiTailscaleTailscalePingUpdateDefault();

  @override
  int get hashCode =>
      latencyMs.hashCode ^
      isDirect.hashCode ^
      endpoint.hashCode ^
      derpRegionId.hashCode ^
      derpRegionCode.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TailscalePingUpdate &&
          runtimeType == other.runtimeType &&
          latencyMs == other.latencyMs &&
          isDirect == other.isDirect &&
          endpoint == other.endpoint &&
          derpRegionId == other.derpRegionId &&
          derpRegionCode == other.derpRegionCode &&
          error == other.error;
}

class TailscaleStatus {
  final List<TailscaleEndpointStatus> endpoints;

  const TailscaleStatus({required this.endpoints});

  static Future<TailscaleStatus> default_() =>
      RustLib.instance.api.crateBackendApiTailscaleTailscaleStatusDefault();

  @override
  int get hashCode => endpoints.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TailscaleStatus &&
          runtimeType == other.runtimeType &&
          endpoints == other.endpoints;
}

class TailscaleUserGroup {
  final PlatformInt64 userId;
  final String loginName;
  final String displayName;
  final String profilePicUrl;
  final List<TailscalePeer> peers;

  const TailscaleUserGroup({
    required this.userId,
    required this.loginName,
    required this.displayName,
    required this.profilePicUrl,
    required this.peers,
  });

  static Future<TailscaleUserGroup> default_() =>
      RustLib.instance.api.crateBackendApiTailscaleTailscaleUserGroupDefault();

  @override
  int get hashCode =>
      userId.hashCode ^
      loginName.hashCode ^
      displayName.hashCode ^
      profilePicUrl.hashCode ^
      peers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TailscaleUserGroup &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          loginName == other.loginName &&
          displayName == other.displayName &&
          profilePicUrl == other.profilePicUrl &&
          peers == other.peers;
}
