// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cache_key`, `clash`, `sing_box`, `surge`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`

class BackendTarget {
  final BackendType backendType;
  final String baseUrl;
  final String? secret;
  final bool allowInsecure;

  const BackendTarget({
    required this.backendType,
    required this.baseUrl,
    this.secret,
    required this.allowInsecure,
  });

  @override
  int get hashCode =>
      backendType.hashCode ^
      baseUrl.hashCode ^
      secret.hashCode ^
      allowInsecure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackendTarget &&
          runtimeType == other.runtimeType &&
          backendType == other.backendType &&
          baseUrl == other.baseUrl &&
          secret == other.secret &&
          allowInsecure == other.allowInsecure;
}

enum BackendType { clash, surge, singBox }
