// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `matches_query`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class Connection {
  final String id;
  final String host;
  final String network;
  final String connType;
  final String sourceIp;
  final int sourcePort;
  final String destinationIp;
  final int destinationPort;
  final String inboundIp;
  final int inboundPort;
  final String inboundName;
  final String dnsMode;
  final int uid;
  final String process;
  final String processPath;
  final String specialProxy;
  final String specialRules;
  final String remoteDestination;
  final String sniffHost;
  final String rule;
  final String rulePayload;
  final List<String> chains;
  final List<String> connectionLogs;
  final BigInt upload;
  final BigInt download;
  final BigInt uploadSpeed;
  final BigInt downloadSpeed;
  final String start;
  final bool isClosed;

  const Connection({
    required this.id,
    required this.host,
    required this.network,
    required this.connType,
    required this.sourceIp,
    required this.sourcePort,
    required this.destinationIp,
    required this.destinationPort,
    required this.inboundIp,
    required this.inboundPort,
    required this.inboundName,
    required this.dnsMode,
    required this.uid,
    required this.process,
    required this.processPath,
    required this.specialProxy,
    required this.specialRules,
    required this.remoteDestination,
    required this.sniffHost,
    required this.rule,
    required this.rulePayload,
    required this.chains,
    required this.connectionLogs,
    required this.upload,
    required this.download,
    required this.uploadSpeed,
    required this.downloadSpeed,
    required this.start,
    required this.isClosed,
  });

  static Future<Connection> default_() =>
      RustLib.instance.api.crateBackendApiTypesConnectionDefault();

  @override
  int get hashCode =>
      id.hashCode ^
      host.hashCode ^
      network.hashCode ^
      connType.hashCode ^
      sourceIp.hashCode ^
      sourcePort.hashCode ^
      destinationIp.hashCode ^
      destinationPort.hashCode ^
      inboundIp.hashCode ^
      inboundPort.hashCode ^
      inboundName.hashCode ^
      dnsMode.hashCode ^
      uid.hashCode ^
      process.hashCode ^
      processPath.hashCode ^
      specialProxy.hashCode ^
      specialRules.hashCode ^
      remoteDestination.hashCode ^
      sniffHost.hashCode ^
      rule.hashCode ^
      rulePayload.hashCode ^
      chains.hashCode ^
      connectionLogs.hashCode ^
      upload.hashCode ^
      download.hashCode ^
      uploadSpeed.hashCode ^
      downloadSpeed.hashCode ^
      start.hashCode ^
      isClosed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Connection &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          host == other.host &&
          network == other.network &&
          connType == other.connType &&
          sourceIp == other.sourceIp &&
          sourcePort == other.sourcePort &&
          destinationIp == other.destinationIp &&
          destinationPort == other.destinationPort &&
          inboundIp == other.inboundIp &&
          inboundPort == other.inboundPort &&
          inboundName == other.inboundName &&
          dnsMode == other.dnsMode &&
          uid == other.uid &&
          process == other.process &&
          processPath == other.processPath &&
          specialProxy == other.specialProxy &&
          specialRules == other.specialRules &&
          remoteDestination == other.remoteDestination &&
          sniffHost == other.sniffHost &&
          rule == other.rule &&
          rulePayload == other.rulePayload &&
          chains == other.chains &&
          connectionLogs == other.connectionLogs &&
          upload == other.upload &&
          download == other.download &&
          uploadSpeed == other.uploadSpeed &&
          downloadSpeed == other.downloadSpeed &&
          start == other.start &&
          isClosed == other.isClosed;
}

class ConnectionGroup {
  final String key;
  final String label;
  final String process;
  final String processPath;
  final String sourceIp;
  final int count;
  final BigInt upload;
  final BigInt download;
  final BigInt uploadSpeed;
  final BigInt downloadSpeed;

  const ConnectionGroup({
    required this.key,
    required this.label,
    required this.process,
    required this.processPath,
    required this.sourceIp,
    required this.count,
    required this.upload,
    required this.download,
    required this.uploadSpeed,
    required this.downloadSpeed,
  });

  static Future<ConnectionGroup> default_() =>
      RustLib.instance.api.crateBackendApiTypesConnectionGroupDefault();

  @override
  int get hashCode =>
      key.hashCode ^
      label.hashCode ^
      process.hashCode ^
      processPath.hashCode ^
      sourceIp.hashCode ^
      count.hashCode ^
      upload.hashCode ^
      download.hashCode ^
      uploadSpeed.hashCode ^
      downloadSpeed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionGroup &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          label == other.label &&
          process == other.process &&
          processPath == other.processPath &&
          sourceIp == other.sourceIp &&
          count == other.count &&
          upload == other.upload &&
          download == other.download &&
          uploadSpeed == other.uploadSpeed &&
          downloadSpeed == other.downloadSpeed;
}

enum ConnectionGroupSort {
  name,
  count,
  upload,
  download,
  uploadSpeed,
  downloadSpeed;

  static Future<ConnectionGroupSort> default_() =>
      RustLib.instance.api.crateBackendApiTypesConnectionGroupSortDefault();
}

class ConnectionStats {
  final BigInt upload;
  final BigInt download;
  final BigInt uploadSpeed;
  final BigInt downloadSpeed;

  const ConnectionStats({
    required this.upload,
    required this.download,
    required this.uploadSpeed,
    required this.downloadSpeed,
  });

  static Future<ConnectionStats> default_() =>
      RustLib.instance.api.crateBackendApiTypesConnectionStatsDefault();

  @override
  int get hashCode =>
      upload.hashCode ^
      download.hashCode ^
      uploadSpeed.hashCode ^
      downloadSpeed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionStats &&
          runtimeType == other.runtimeType &&
          upload == other.upload &&
          download == other.download &&
          uploadSpeed == other.uploadSpeed &&
          downloadSpeed == other.downloadSpeed;
}

class ConnectionWindow {
  final int total;
  final List<Connection> rows;

  const ConnectionWindow({required this.total, required this.rows});

  static Future<ConnectionWindow> default_() =>
      RustLib.instance.api.crateBackendApiTypesConnectionWindowDefault();

  @override
  int get hashCode => total.hashCode ^ rows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionWindow &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          rows == other.rows;
}

class ConnectionsFrame {
  final int activeCount;
  final int closedCount;
  final ConnectionsTotals totals;
  final bool isInitial;

  const ConnectionsFrame({
    required this.activeCount,
    required this.closedCount,
    required this.totals,
    required this.isInitial,
  });

  static Future<ConnectionsFrame> default_() =>
      RustLib.instance.api.crateBackendApiTypesConnectionsFrameDefault();

  @override
  int get hashCode =>
      activeCount.hashCode ^
      closedCount.hashCode ^
      totals.hashCode ^
      isInitial.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionsFrame &&
          runtimeType == other.runtimeType &&
          activeCount == other.activeCount &&
          closedCount == other.closedCount &&
          totals == other.totals &&
          isInitial == other.isInitial;
}

enum ConnectionsListKind { active, closed }

enum ConnectionsSort {
  time,
  upload,
  download,
  uploadSpeed,
  downloadSpeed,
  process;

  static Future<ConnectionsSort> default_() =>
      RustLib.instance.api.crateBackendApiTypesConnectionsSortDefault();
}

class ConnectionsTotals {
  final BigInt upload;
  final BigInt download;
  final BigInt memory;
  final int connectionsIn;
  final int connectionsOut;

  const ConnectionsTotals({
    required this.upload,
    required this.download,
    required this.memory,
    required this.connectionsIn,
    required this.connectionsOut,
  });

  static Future<ConnectionsTotals> default_() =>
      RustLib.instance.api.crateBackendApiTypesConnectionsTotalsDefault();

  @override
  int get hashCode =>
      upload.hashCode ^
      download.hashCode ^
      memory.hashCode ^
      connectionsIn.hashCode ^
      connectionsOut.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionsTotals &&
          runtimeType == other.runtimeType &&
          upload == other.upload &&
          download == other.download &&
          memory == other.memory &&
          connectionsIn == other.connectionsIn &&
          connectionsOut == other.connectionsOut;
}

class ControllerConfig {
  final String? mode;
  final List<String> modeOptions;
  final String? logLevel;
  final bool? tunEnabled;
  final bool? allowLan;
  final bool? ipv6;
  final bool? tcpConcurrent;
  final int? port;
  final int? socksPort;
  final int? mixedPort;

  const ControllerConfig({
    this.mode,
    required this.modeOptions,
    this.logLevel,
    this.tunEnabled,
    this.allowLan,
    this.ipv6,
    this.tcpConcurrent,
    this.port,
    this.socksPort,
    this.mixedPort,
  });

  static Future<ControllerConfig> default_() =>
      RustLib.instance.api.crateBackendApiTypesControllerConfigDefault();

  @override
  int get hashCode =>
      mode.hashCode ^
      modeOptions.hashCode ^
      logLevel.hashCode ^
      tunEnabled.hashCode ^
      allowLan.hashCode ^
      ipv6.hashCode ^
      tcpConcurrent.hashCode ^
      port.hashCode ^
      socksPort.hashCode ^
      mixedPort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ControllerConfig &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          modeOptions == other.modeOptions &&
          logLevel == other.logLevel &&
          tunEnabled == other.tunEnabled &&
          allowLan == other.allowLan &&
          ipv6 == other.ipv6 &&
          tcpConcurrent == other.tcpConcurrent &&
          port == other.port &&
          socksPort == other.socksPort &&
          mixedPort == other.mixedPort;
}

class GroupDelayEntry {
  final String name;
  final int delay;

  const GroupDelayEntry({required this.name, required this.delay});

  static Future<GroupDelayEntry> default_() =>
      RustLib.instance.api.crateBackendApiTypesGroupDelayEntryDefault();

  @override
  int get hashCode => name.hashCode ^ delay.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupDelayEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          delay == other.delay;
}

class LogEntry {
  final BigInt id;
  final String time;
  final String level;
  final String message;

  const LogEntry({
    required this.id,
    required this.time,
    required this.level,
    required this.message,
  });

  static Future<LogEntry> default_() =>
      RustLib.instance.api.crateBackendApiTypesLogEntryDefault();

  @override
  int get hashCode =>
      id.hashCode ^ time.hashCode ^ level.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          time == other.time &&
          level == other.level &&
          message == other.message;
}

class LogWindow {
  final int total;
  final int offset;
  final List<LogEntry> rows;

  const LogWindow({
    required this.total,
    required this.offset,
    required this.rows,
  });

  static Future<LogWindow> default_() =>
      RustLib.instance.api.crateBackendApiTypesLogWindowDefault();

  @override
  int get hashCode => total.hashCode ^ offset.hashCode ^ rows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogWindow &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          offset == other.offset &&
          rows == other.rows;
}

class LogsFrame {
  final int total;
  final BigInt latestId;
  final bool isInitial;

  const LogsFrame({
    required this.total,
    required this.latestId,
    required this.isInitial,
  });

  static Future<LogsFrame> default_() =>
      RustLib.instance.api.crateBackendApiTypesLogsFrameDefault();

  @override
  int get hashCode => total.hashCode ^ latestId.hashCode ^ isInitial.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogsFrame &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          latestId == other.latestId &&
          isInitial == other.isInitial;
}

class MemorySample {
  final BigInt inuse;
  final BigInt oslimit;
  final int goroutines;

  const MemorySample({
    required this.inuse,
    required this.oslimit,
    required this.goroutines,
  });

  static Future<MemorySample> default_() =>
      RustLib.instance.api.crateBackendApiTypesMemorySampleDefault();

  @override
  int get hashCode => inuse.hashCode ^ oslimit.hashCode ^ goroutines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemorySample &&
          runtimeType == other.runtimeType &&
          inuse == other.inuse &&
          oslimit == other.oslimit &&
          goroutines == other.goroutines;
}

class ProxyCatalog {
  final List<ProxyGroupEntry> groups;
  final List<String> iconUrls;

  const ProxyCatalog({required this.groups, required this.iconUrls});

  static Future<ProxyCatalog> default_() =>
      RustLib.instance.api.crateBackendApiTypesProxyCatalogDefault();

  @override
  int get hashCode => groups.hashCode ^ iconUrls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyCatalog &&
          runtimeType == other.runtimeType &&
          groups == other.groups &&
          iconUrls == other.iconUrls;
}

class ProxyDelayEntry {
  final String name;
  final int delay;

  const ProxyDelayEntry({required this.name, required this.delay});

  static Future<ProxyDelayEntry> default_() =>
      RustLib.instance.api.crateBackendApiTypesProxyDelayEntryDefault();

  @override
  int get hashCode => name.hashCode ^ delay.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyDelayEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          delay == other.delay;
}

class ProxyDelayEvent {
  final String name;
  final int delay;
  final int windowOffset;
  final int windowMembersHash;
  final List<ProxyMemberEntry> windowEntries;

  const ProxyDelayEvent({
    required this.name,
    required this.delay,
    required this.windowOffset,
    required this.windowMembersHash,
    required this.windowEntries,
  });

  static Future<ProxyDelayEvent> default_() =>
      RustLib.instance.api.crateBackendApiTypesProxyDelayEventDefault();

  @override
  int get hashCode =>
      name.hashCode ^
      delay.hashCode ^
      windowOffset.hashCode ^
      windowMembersHash.hashCode ^
      windowEntries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyDelayEvent &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          delay == other.delay &&
          windowOffset == other.windowOffset &&
          windowMembersHash == other.windowMembersHash &&
          windowEntries == other.windowEntries;
}

class ProxyGroupEntry {
  final String name;
  final String proxyType;
  final bool selectable;
  final String icon;
  final int memberCount;
  final int membersHash;
  final String now;
  final int nowDelay;
  final String testUrl;
  final String fixed;

  const ProxyGroupEntry({
    required this.name,
    required this.proxyType,
    required this.selectable,
    required this.icon,
    required this.memberCount,
    required this.membersHash,
    required this.now,
    required this.nowDelay,
    required this.testUrl,
    required this.fixed,
  });

  static Future<ProxyGroupEntry> default_() =>
      RustLib.instance.api.crateBackendApiTypesProxyGroupEntryDefault();

  @override
  int get hashCode =>
      name.hashCode ^
      proxyType.hashCode ^
      selectable.hashCode ^
      icon.hashCode ^
      memberCount.hashCode ^
      membersHash.hashCode ^
      now.hashCode ^
      nowDelay.hashCode ^
      testUrl.hashCode ^
      fixed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyGroupEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          proxyType == other.proxyType &&
          selectable == other.selectable &&
          icon == other.icon &&
          memberCount == other.memberCount &&
          membersHash == other.membersHash &&
          now == other.now &&
          nowDelay == other.nowDelay &&
          testUrl == other.testUrl &&
          fixed == other.fixed;
}

class ProxyMemberEntry {
  final String name;
  final String proxyType;
  final int delay;

  const ProxyMemberEntry({
    required this.name,
    required this.proxyType,
    required this.delay,
  });

  static Future<ProxyMemberEntry> default_() =>
      RustLib.instance.api.crateBackendApiTypesProxyMemberEntryDefault();

  @override
  int get hashCode => name.hashCode ^ proxyType.hashCode ^ delay.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyMemberEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          proxyType == other.proxyType &&
          delay == other.delay;
}

class ProxyMemberSection {
  final String provider;
  final int offset;
  final int count;

  const ProxyMemberSection({
    required this.provider,
    required this.offset,
    required this.count,
  });

  static Future<ProxyMemberSection> default_() =>
      RustLib.instance.api.crateBackendApiTypesProxyMemberSectionDefault();

  @override
  int get hashCode => provider.hashCode ^ offset.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyMemberSection &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          offset == other.offset &&
          count == other.count;
}

enum ProxyMemberSort {
  original,
  name,
  delay;

  static Future<ProxyMemberSort> default_() =>
      RustLib.instance.api.crateBackendApiTypesProxyMemberSortDefault();
}

class ProxyMemberWindow {
  final int offset;
  final int currentIndex;
  final List<ProxyMemberEntry> entries;
  final List<ProxyMemberSection> sections;

  const ProxyMemberWindow({
    required this.offset,
    required this.currentIndex,
    required this.entries,
    required this.sections,
  });

  static Future<ProxyMemberWindow> default_() =>
      RustLib.instance.api.crateBackendApiTypesProxyMemberWindowDefault();

  @override
  int get hashCode =>
      offset.hashCode ^
      currentIndex.hashCode ^
      entries.hashCode ^
      sections.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyMemberWindow &&
          runtimeType == other.runtimeType &&
          offset == other.offset &&
          currentIndex == other.currentIndex &&
          entries == other.entries &&
          sections == other.sections;
}

class ProxyProviderEntry {
  final String name;
  final String vehicleType;
  final int proxies;
  final String updatedAt;
  final bool updatable;
  final bool hasSubscriptionInfo;
  final BigInt subscriptionUpload;
  final BigInt subscriptionDownload;
  final BigInt subscriptionTotal;
  final BigInt subscriptionExpire;

  const ProxyProviderEntry({
    required this.name,
    required this.vehicleType,
    required this.proxies,
    required this.updatedAt,
    required this.updatable,
    required this.hasSubscriptionInfo,
    required this.subscriptionUpload,
    required this.subscriptionDownload,
    required this.subscriptionTotal,
    required this.subscriptionExpire,
  });

  static Future<ProxyProviderEntry> default_() =>
      RustLib.instance.api.crateBackendApiTypesProxyProviderEntryDefault();

  @override
  int get hashCode =>
      name.hashCode ^
      vehicleType.hashCode ^
      proxies.hashCode ^
      updatedAt.hashCode ^
      updatable.hashCode ^
      hasSubscriptionInfo.hashCode ^
      subscriptionUpload.hashCode ^
      subscriptionDownload.hashCode ^
      subscriptionTotal.hashCode ^
      subscriptionExpire.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyProviderEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          vehicleType == other.vehicleType &&
          proxies == other.proxies &&
          updatedAt == other.updatedAt &&
          updatable == other.updatable &&
          hasSubscriptionInfo == other.hasSubscriptionInfo &&
          subscriptionUpload == other.subscriptionUpload &&
          subscriptionDownload == other.subscriptionDownload &&
          subscriptionTotal == other.subscriptionTotal &&
          subscriptionExpire == other.subscriptionExpire;
}

class ProxyProviderNodeWindow {
  final int total;
  final int filtered;
  final int offset;
  final List<ProxyMemberEntry> entries;

  const ProxyProviderNodeWindow({
    required this.total,
    required this.filtered,
    required this.offset,
    required this.entries,
  });

  static Future<ProxyProviderNodeWindow> default_() =>
      RustLib.instance.api.crateBackendApiTypesProxyProviderNodeWindowDefault();

  @override
  int get hashCode =>
      total.hashCode ^ filtered.hashCode ^ offset.hashCode ^ entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyProviderNodeWindow &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          filtered == other.filtered &&
          offset == other.offset &&
          entries == other.entries;
}

class RuleEntry {
  final int index;
  final String ruleType;
  final String payload;
  final String proxy;
  final List<String> extraParams;
  final bool disabled;
  final BigInt hitCount;
  final String hitAt;
  final BigInt missCount;
  final String missAt;
  final bool hasExtra;

  const RuleEntry({
    required this.index,
    required this.ruleType,
    required this.payload,
    required this.proxy,
    required this.extraParams,
    required this.disabled,
    required this.hitCount,
    required this.hitAt,
    required this.missCount,
    required this.missAt,
    required this.hasExtra,
  });

  static Future<RuleEntry> default_() =>
      RustLib.instance.api.crateBackendApiTypesRuleEntryDefault();

  @override
  int get hashCode =>
      index.hashCode ^
      ruleType.hashCode ^
      payload.hashCode ^
      proxy.hashCode ^
      extraParams.hashCode ^
      disabled.hashCode ^
      hitCount.hashCode ^
      hitAt.hashCode ^
      missCount.hashCode ^
      missAt.hashCode ^
      hasExtra.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuleEntry &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          ruleType == other.ruleType &&
          payload == other.payload &&
          proxy == other.proxy &&
          extraParams == other.extraParams &&
          disabled == other.disabled &&
          hitCount == other.hitCount &&
          hitAt == other.hitAt &&
          missCount == other.missCount &&
          missAt == other.missAt &&
          hasExtra == other.hasExtra;
}

class RuleProviderEntry {
  final String name;
  final String vehicleType;
  final String behavior;
  final String format;
  final int ruleCount;
  final String updatedAt;
  final bool updatable;

  const RuleProviderEntry({
    required this.name,
    required this.vehicleType,
    required this.behavior,
    required this.format,
    required this.ruleCount,
    required this.updatedAt,
    required this.updatable,
  });

  static Future<RuleProviderEntry> default_() =>
      RustLib.instance.api.crateBackendApiTypesRuleProviderEntryDefault();

  @override
  int get hashCode =>
      name.hashCode ^
      vehicleType.hashCode ^
      behavior.hashCode ^
      format.hashCode ^
      ruleCount.hashCode ^
      updatedAt.hashCode ^
      updatable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuleProviderEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          vehicleType == other.vehicleType &&
          behavior == other.behavior &&
          format == other.format &&
          ruleCount == other.ruleCount &&
          updatedAt == other.updatedAt &&
          updatable == other.updatable;
}

class RulesSummary {
  final int total;
  final int filtered;

  const RulesSummary({required this.total, required this.filtered});

  static Future<RulesSummary> default_() =>
      RustLib.instance.api.crateBackendApiTypesRulesSummaryDefault();

  @override
  int get hashCode => total.hashCode ^ filtered.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RulesSummary &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          filtered == other.filtered;
}

class SessionBootstrap {
  final int ruleCount;

  const SessionBootstrap({required this.ruleCount});

  static Future<SessionBootstrap> default_() =>
      RustLib.instance.api.crateBackendApiTypesSessionBootstrapDefault();

  @override
  int get hashCode => ruleCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionBootstrap &&
          runtimeType == other.runtimeType &&
          ruleCount == other.ruleCount;
}

class TrafficSample {
  final BigInt up;
  final BigInt down;
  final BigInt upTotal;
  final BigInt downTotal;

  const TrafficSample({
    required this.up,
    required this.down,
    required this.upTotal,
    required this.downTotal,
  });

  static Future<TrafficSample> default_() =>
      RustLib.instance.api.crateBackendApiTypesTrafficSampleDefault();

  @override
  int get hashCode =>
      up.hashCode ^ down.hashCode ^ upTotal.hashCode ^ downTotal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrafficSample &&
          runtimeType == other.runtimeType &&
          up == other.up &&
          down == other.down &&
          upTotal == other.upTotal &&
          downTotal == other.downTotal;
}

class VersionInfo {
  final String version;
  final bool isCmfa;
  final bool isStash;
  final bool supportsCoreConfig;
  final bool supportsCoreActions;
  final bool supportsCoreManagement;
  final bool supportsCacheFlush;
  final bool supportsMemory;
  final bool supportsTailscale;
  final bool supportsDiagnostics;

  const VersionInfo({
    required this.version,
    required this.isCmfa,
    required this.isStash,
    required this.supportsCoreConfig,
    required this.supportsCoreActions,
    required this.supportsCoreManagement,
    required this.supportsCacheFlush,
    required this.supportsMemory,
    required this.supportsTailscale,
    required this.supportsDiagnostics,
  });

  static Future<VersionInfo> default_() =>
      RustLib.instance.api.crateBackendApiTypesVersionInfoDefault();

  @override
  int get hashCode =>
      version.hashCode ^
      isCmfa.hashCode ^
      isStash.hashCode ^
      supportsCoreConfig.hashCode ^
      supportsCoreActions.hashCode ^
      supportsCoreManagement.hashCode ^
      supportsCacheFlush.hashCode ^
      supportsMemory.hashCode ^
      supportsTailscale.hashCode ^
      supportsDiagnostics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VersionInfo &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          isCmfa == other.isCmfa &&
          isStash == other.isStash &&
          supportsCoreConfig == other.supportsCoreConfig &&
          supportsCoreActions == other.supportsCoreActions &&
          supportsCoreManagement == other.supportsCoreManagement &&
          supportsCacheFlush == other.supportsCacheFlush &&
          supportsMemory == other.supportsMemory &&
          supportsTailscale == other.supportsTailscale &&
          supportsDiagnostics == other.supportsDiagnostics;
}
