// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `client`, `urlencode`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// One mihomo external-controller endpoint.
class MihomoTarget {
  final String baseUrl;
  final String? secret;

  /// Skip TLS cert validation for https/wss (self-signed backends).
  final bool allowInsecure;

  const MihomoTarget({
    required this.baseUrl,
    this.secret,
    required this.allowInsecure,
  });

  @override
  int get hashCode =>
      baseUrl.hashCode ^ secret.hashCode ^ allowInsecure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MihomoTarget &&
          runtimeType == other.runtimeType &&
          baseUrl == other.baseUrl &&
          secret == other.secret &&
          allowInsecure == other.allowInsecure;
}
