// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'backend/api/connections.dart';
import 'backend/api/control.dart';
import 'backend/api/diagnostics.dart';
import 'backend/api/providers.dart';
import 'backend/api/proxies.dart';
import 'backend/api/proxy_delay.dart';
import 'backend/api/resources.dart';
import 'backend/api/rules.dart';
import 'backend/api/session.dart';
import 'backend/api/streams.dart';
import 'backend/api/tailscale.dart';
import 'backend/api/target.dart';
import 'backend/api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'utils/error.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<ConnectionsFrame> dco_decode_StreamSink_connections_frame_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<LogsFrame> dco_decode_StreamSink_logs_frame_Sse(dynamic raw);

  @protected
  RustStreamSink<MemorySample> dco_decode_StreamSink_memory_sample_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<NetworkQualityProgress>
  dco_decode_StreamSink_network_quality_progress_Sse(dynamic raw);

  @protected
  RustStreamSink<ProxyDelayEvent> dco_decode_StreamSink_proxy_delay_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<StunTestProgress> dco_decode_StreamSink_stun_test_progress_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<TailscalePingUpdate>
  dco_decode_StreamSink_tailscale_ping_update_Sse(dynamic raw);

  @protected
  RustStreamSink<TailscaleStatus> dco_decode_StreamSink_tailscale_status_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<TrafficSample> dco_decode_StreamSink_traffic_sample_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BackendTarget dco_decode_backend_target(dynamic raw);

  @protected
  BackendType dco_decode_backend_type(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BackendTarget dco_decode_box_autoadd_backend_target(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  ConnectionStats dco_decode_box_autoadd_connection_stats(dynamic raw);

  @protected
  TailscalePeer dco_decode_box_autoadd_tailscale_peer(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  Connection dco_decode_connection(dynamic raw);

  @protected
  ConnectionGroup dco_decode_connection_group(dynamic raw);

  @protected
  ConnectionGroupSort dco_decode_connection_group_sort(dynamic raw);

  @protected
  ConnectionStats dco_decode_connection_stats(dynamic raw);

  @protected
  ConnectionWindow dco_decode_connection_window(dynamic raw);

  @protected
  ConnectionsFrame dco_decode_connections_frame(dynamic raw);

  @protected
  ConnectionsListKind dco_decode_connections_list_kind(dynamic raw);

  @protected
  ConnectionsSort dco_decode_connections_sort(dynamic raw);

  @protected
  ConnectionsTotals dco_decode_connections_totals(dynamic raw);

  @protected
  ControllerConfig dco_decode_controller_config(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GroupDelayEntry dco_decode_group_delay_entry(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Connection> dco_decode_list_connection(dynamic raw);

  @protected
  List<ConnectionGroup> dco_decode_list_connection_group(dynamic raw);

  @protected
  List<GroupDelayEntry> dco_decode_list_group_delay_entry(dynamic raw);

  @protected
  List<LogEntry> dco_decode_list_log_entry(dynamic raw);

  @protected
  List<OutboundEntry> dco_decode_list_outbound_entry(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProxyDelayEntry> dco_decode_list_proxy_delay_entry(dynamic raw);

  @protected
  List<ProxyGroupEntry> dco_decode_list_proxy_group_entry(dynamic raw);

  @protected
  List<ProxyMemberEntry> dco_decode_list_proxy_member_entry(dynamic raw);

  @protected
  List<ProxyMemberSection> dco_decode_list_proxy_member_section(dynamic raw);

  @protected
  List<ProxyProviderEntry> dco_decode_list_proxy_provider_entry(dynamic raw);

  @protected
  List<RuleEntry> dco_decode_list_rule_entry(dynamic raw);

  @protected
  List<RuleProviderEntry> dco_decode_list_rule_provider_entry(dynamic raw);

  @protected
  List<TailscaleEndpointStatus> dco_decode_list_tailscale_endpoint_status(
    dynamic raw,
  );

  @protected
  List<TailscalePeer> dco_decode_list_tailscale_peer(dynamic raw);

  @protected
  List<TailscaleUserGroup> dco_decode_list_tailscale_user_group(dynamic raw);

  @protected
  LogEntry dco_decode_log_entry(dynamic raw);

  @protected
  LogWindow dco_decode_log_window(dynamic raw);

  @protected
  LogsFrame dco_decode_logs_frame(dynamic raw);

  @protected
  MemorySample dco_decode_memory_sample(dynamic raw);

  @protected
  MihomoError dco_decode_mihomo_error(dynamic raw);

  @protected
  NetworkQualityProgress dco_decode_network_quality_progress(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  ConnectionStats? dco_decode_opt_box_autoadd_connection_stats(dynamic raw);

  @protected
  TailscalePeer? dco_decode_opt_box_autoadd_tailscale_peer(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  OutboundEntry dco_decode_outbound_entry(dynamic raw);

  @protected
  ProxyCatalog dco_decode_proxy_catalog(dynamic raw);

  @protected
  ProxyDelayEntry dco_decode_proxy_delay_entry(dynamic raw);

  @protected
  ProxyDelayEvent dco_decode_proxy_delay_event(dynamic raw);

  @protected
  ProxyGroupEntry dco_decode_proxy_group_entry(dynamic raw);

  @protected
  ProxyMemberEntry dco_decode_proxy_member_entry(dynamic raw);

  @protected
  ProxyMemberSection dco_decode_proxy_member_section(dynamic raw);

  @protected
  ProxyMemberSort dco_decode_proxy_member_sort(dynamic raw);

  @protected
  ProxyMemberWindow dco_decode_proxy_member_window(dynamic raw);

  @protected
  ProxyProviderEntry dco_decode_proxy_provider_entry(dynamic raw);

  @protected
  ProxyProviderNodeWindow dco_decode_proxy_provider_node_window(dynamic raw);

  @protected
  RuleEntry dco_decode_rule_entry(dynamic raw);

  @protected
  RuleProviderEntry dco_decode_rule_provider_entry(dynamic raw);

  @protected
  RulesSummary dco_decode_rules_summary(dynamic raw);

  @protected
  SessionBootstrap dco_decode_session_bootstrap(dynamic raw);

  @protected
  StunTestProgress dco_decode_stun_test_progress(dynamic raw);

  @protected
  TailscaleEndpointStatus dco_decode_tailscale_endpoint_status(dynamic raw);

  @protected
  TailscalePeer dco_decode_tailscale_peer(dynamic raw);

  @protected
  TailscalePingUpdate dco_decode_tailscale_ping_update(dynamic raw);

  @protected
  TailscaleStatus dco_decode_tailscale_status(dynamic raw);

  @protected
  TailscaleUserGroup dco_decode_tailscale_user_group(dynamic raw);

  @protected
  TrafficSample dco_decode_traffic_sample(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VersionInfo dco_decode_version_info(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<ConnectionsFrame> sse_decode_StreamSink_connections_frame_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LogsFrame> sse_decode_StreamSink_logs_frame_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<MemorySample> sse_decode_StreamSink_memory_sample_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<NetworkQualityProgress>
  sse_decode_StreamSink_network_quality_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ProxyDelayEvent> sse_decode_StreamSink_proxy_delay_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<StunTestProgress> sse_decode_StreamSink_stun_test_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TailscalePingUpdate>
  sse_decode_StreamSink_tailscale_ping_update_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<TailscaleStatus> sse_decode_StreamSink_tailscale_status_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TrafficSample> sse_decode_StreamSink_traffic_sample_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BackendTarget sse_decode_backend_target(SseDeserializer deserializer);

  @protected
  BackendType sse_decode_backend_type(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BackendTarget sse_decode_box_autoadd_backend_target(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ConnectionStats sse_decode_box_autoadd_connection_stats(
    SseDeserializer deserializer,
  );

  @protected
  TailscalePeer sse_decode_box_autoadd_tailscale_peer(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Connection sse_decode_connection(SseDeserializer deserializer);

  @protected
  ConnectionGroup sse_decode_connection_group(SseDeserializer deserializer);

  @protected
  ConnectionGroupSort sse_decode_connection_group_sort(
    SseDeserializer deserializer,
  );

  @protected
  ConnectionStats sse_decode_connection_stats(SseDeserializer deserializer);

  @protected
  ConnectionWindow sse_decode_connection_window(SseDeserializer deserializer);

  @protected
  ConnectionsFrame sse_decode_connections_frame(SseDeserializer deserializer);

  @protected
  ConnectionsListKind sse_decode_connections_list_kind(
    SseDeserializer deserializer,
  );

  @protected
  ConnectionsSort sse_decode_connections_sort(SseDeserializer deserializer);

  @protected
  ConnectionsTotals sse_decode_connections_totals(SseDeserializer deserializer);

  @protected
  ControllerConfig sse_decode_controller_config(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GroupDelayEntry sse_decode_group_delay_entry(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Connection> sse_decode_list_connection(SseDeserializer deserializer);

  @protected
  List<ConnectionGroup> sse_decode_list_connection_group(
    SseDeserializer deserializer,
  );

  @protected
  List<GroupDelayEntry> sse_decode_list_group_delay_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<LogEntry> sse_decode_list_log_entry(SseDeserializer deserializer);

  @protected
  List<OutboundEntry> sse_decode_list_outbound_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProxyDelayEntry> sse_decode_list_proxy_delay_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<ProxyGroupEntry> sse_decode_list_proxy_group_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<ProxyMemberEntry> sse_decode_list_proxy_member_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<ProxyMemberSection> sse_decode_list_proxy_member_section(
    SseDeserializer deserializer,
  );

  @protected
  List<ProxyProviderEntry> sse_decode_list_proxy_provider_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<RuleEntry> sse_decode_list_rule_entry(SseDeserializer deserializer);

  @protected
  List<RuleProviderEntry> sse_decode_list_rule_provider_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<TailscaleEndpointStatus> sse_decode_list_tailscale_endpoint_status(
    SseDeserializer deserializer,
  );

  @protected
  List<TailscalePeer> sse_decode_list_tailscale_peer(
    SseDeserializer deserializer,
  );

  @protected
  List<TailscaleUserGroup> sse_decode_list_tailscale_user_group(
    SseDeserializer deserializer,
  );

  @protected
  LogEntry sse_decode_log_entry(SseDeserializer deserializer);

  @protected
  LogWindow sse_decode_log_window(SseDeserializer deserializer);

  @protected
  LogsFrame sse_decode_logs_frame(SseDeserializer deserializer);

  @protected
  MemorySample sse_decode_memory_sample(SseDeserializer deserializer);

  @protected
  MihomoError sse_decode_mihomo_error(SseDeserializer deserializer);

  @protected
  NetworkQualityProgress sse_decode_network_quality_progress(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ConnectionStats? sse_decode_opt_box_autoadd_connection_stats(
    SseDeserializer deserializer,
  );

  @protected
  TailscalePeer? sse_decode_opt_box_autoadd_tailscale_peer(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  OutboundEntry sse_decode_outbound_entry(SseDeserializer deserializer);

  @protected
  ProxyCatalog sse_decode_proxy_catalog(SseDeserializer deserializer);

  @protected
  ProxyDelayEntry sse_decode_proxy_delay_entry(SseDeserializer deserializer);

  @protected
  ProxyDelayEvent sse_decode_proxy_delay_event(SseDeserializer deserializer);

  @protected
  ProxyGroupEntry sse_decode_proxy_group_entry(SseDeserializer deserializer);

  @protected
  ProxyMemberEntry sse_decode_proxy_member_entry(SseDeserializer deserializer);

  @protected
  ProxyMemberSection sse_decode_proxy_member_section(
    SseDeserializer deserializer,
  );

  @protected
  ProxyMemberSort sse_decode_proxy_member_sort(SseDeserializer deserializer);

  @protected
  ProxyMemberWindow sse_decode_proxy_member_window(
    SseDeserializer deserializer,
  );

  @protected
  ProxyProviderEntry sse_decode_proxy_provider_entry(
    SseDeserializer deserializer,
  );

  @protected
  ProxyProviderNodeWindow sse_decode_proxy_provider_node_window(
    SseDeserializer deserializer,
  );

  @protected
  RuleEntry sse_decode_rule_entry(SseDeserializer deserializer);

  @protected
  RuleProviderEntry sse_decode_rule_provider_entry(
    SseDeserializer deserializer,
  );

  @protected
  RulesSummary sse_decode_rules_summary(SseDeserializer deserializer);

  @protected
  SessionBootstrap sse_decode_session_bootstrap(SseDeserializer deserializer);

  @protected
  StunTestProgress sse_decode_stun_test_progress(SseDeserializer deserializer);

  @protected
  TailscaleEndpointStatus sse_decode_tailscale_endpoint_status(
    SseDeserializer deserializer,
  );

  @protected
  TailscalePeer sse_decode_tailscale_peer(SseDeserializer deserializer);

  @protected
  TailscalePingUpdate sse_decode_tailscale_ping_update(
    SseDeserializer deserializer,
  );

  @protected
  TailscaleStatus sse_decode_tailscale_status(SseDeserializer deserializer);

  @protected
  TailscaleUserGroup sse_decode_tailscale_user_group(
    SseDeserializer deserializer,
  );

  @protected
  TrafficSample sse_decode_traffic_sample(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VersionInfo sse_decode_version_info(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_connections_frame_Sse(
    RustStreamSink<ConnectionsFrame> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_logs_frame_Sse(
    RustStreamSink<LogsFrame> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_memory_sample_Sse(
    RustStreamSink<MemorySample> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_network_quality_progress_Sse(
    RustStreamSink<NetworkQualityProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_proxy_delay_event_Sse(
    RustStreamSink<ProxyDelayEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_stun_test_progress_Sse(
    RustStreamSink<StunTestProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_tailscale_ping_update_Sse(
    RustStreamSink<TailscalePingUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_tailscale_status_Sse(
    RustStreamSink<TailscaleStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_traffic_sample_Sse(
    RustStreamSink<TrafficSample> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_backend_target(BackendTarget self, SseSerializer serializer);

  @protected
  void sse_encode_backend_type(BackendType self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_backend_target(
    BackendTarget self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_connection_stats(
    ConnectionStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_tailscale_peer(
    TailscalePeer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_connection(Connection self, SseSerializer serializer);

  @protected
  void sse_encode_connection_group(
    ConnectionGroup self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_group_sort(
    ConnectionGroupSort self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_stats(
    ConnectionStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_window(
    ConnectionWindow self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connections_frame(
    ConnectionsFrame self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connections_list_kind(
    ConnectionsListKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connections_sort(
    ConnectionsSort self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connections_totals(
    ConnectionsTotals self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_controller_config(
    ControllerConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_group_delay_entry(
    GroupDelayEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_connection(
    List<Connection> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_connection_group(
    List<ConnectionGroup> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_group_delay_entry(
    List<GroupDelayEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_log_entry(List<LogEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_outbound_entry(
    List<OutboundEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_proxy_delay_entry(
    List<ProxyDelayEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_proxy_group_entry(
    List<ProxyGroupEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_proxy_member_entry(
    List<ProxyMemberEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_proxy_member_section(
    List<ProxyMemberSection> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_proxy_provider_entry(
    List<ProxyProviderEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rule_entry(
    List<RuleEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rule_provider_entry(
    List<RuleProviderEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tailscale_endpoint_status(
    List<TailscaleEndpointStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tailscale_peer(
    List<TailscalePeer> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tailscale_user_group(
    List<TailscaleUserGroup> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_log_entry(LogEntry self, SseSerializer serializer);

  @protected
  void sse_encode_log_window(LogWindow self, SseSerializer serializer);

  @protected
  void sse_encode_logs_frame(LogsFrame self, SseSerializer serializer);

  @protected
  void sse_encode_memory_sample(MemorySample self, SseSerializer serializer);

  @protected
  void sse_encode_mihomo_error(MihomoError self, SseSerializer serializer);

  @protected
  void sse_encode_network_quality_progress(
    NetworkQualityProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_connection_stats(
    ConnectionStats? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_tailscale_peer(
    TailscalePeer? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_outbound_entry(OutboundEntry self, SseSerializer serializer);

  @protected
  void sse_encode_proxy_catalog(ProxyCatalog self, SseSerializer serializer);

  @protected
  void sse_encode_proxy_delay_entry(
    ProxyDelayEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proxy_delay_event(
    ProxyDelayEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proxy_group_entry(
    ProxyGroupEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proxy_member_entry(
    ProxyMemberEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proxy_member_section(
    ProxyMemberSection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proxy_member_sort(
    ProxyMemberSort self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proxy_member_window(
    ProxyMemberWindow self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proxy_provider_entry(
    ProxyProviderEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proxy_provider_node_window(
    ProxyProviderNodeWindow self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rule_entry(RuleEntry self, SseSerializer serializer);

  @protected
  void sse_encode_rule_provider_entry(
    RuleProviderEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rules_summary(RulesSummary self, SseSerializer serializer);

  @protected
  void sse_encode_session_bootstrap(
    SessionBootstrap self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stun_test_progress(
    StunTestProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tailscale_endpoint_status(
    TailscaleEndpointStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tailscale_peer(TailscalePeer self, SseSerializer serializer);

  @protected
  void sse_encode_tailscale_ping_update(
    TailscalePingUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tailscale_status(
    TailscaleStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tailscale_user_group(
    TailscaleUserGroup self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_traffic_sample(TrafficSample self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_version_info(VersionInfo self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
