// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../api.dart';
import '../../frb_generated.dart';
import '../../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cached_group_member_names`, `group_order`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// Structured proxy + group catalog. Rust parses mihomo's `/proxies`, applies
/// hidden-group filtering, preserves UI ordering (`GLOBAL.all`), caches full
/// group members in Rust, and returns only group summaries to Dart.
Future<ProxyCatalog> proxyCatalog({
  required MihomoTarget target,
  required bool includeHidden,
  required String filter,
}) => RustLib.instance.api.crateApiProxiesCatalogProxyCatalog(
  target: target,
  includeHidden: includeHidden,
  filter: filter,
);

/// Windowed members for one proxy group. The full member list stays in Rust so
/// very large groups do not cross the bridge on every catalog refresh.
Future<List<ProxyMemberEntry>> proxyGroupMembers({
  required MihomoTarget target,
  required String group,
  required int offset,
  required int limit,
  required ProxyMemberSort memberSort,
}) => RustLib.instance.api.crateApiProxiesCatalogProxyGroupMembers(
  target: target,
  group: group,
  offset: offset,
  limit: limit,
  memberSort: memberSort,
);

class ProxyCatalog {
  final List<ProxyGroupEntry> groups;
  final List<String> iconUrls;

  const ProxyCatalog({required this.groups, required this.iconUrls});

  static Future<ProxyCatalog> default_() =>
      RustLib.instance.api.crateApiProxiesCatalogProxyCatalogDefault();

  @override
  int get hashCode => groups.hashCode ^ iconUrls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyCatalog &&
          runtimeType == other.runtimeType &&
          groups == other.groups &&
          iconUrls == other.iconUrls;
}

class ProxyGroupEntry {
  final String name;
  final String proxyType;
  final String icon;
  final int memberCount;
  final int membersHash;
  final String now;
  final String testUrl;
  final String fixed;

  const ProxyGroupEntry({
    required this.name,
    required this.proxyType,
    required this.icon,
    required this.memberCount,
    required this.membersHash,
    required this.now,
    required this.testUrl,
    required this.fixed,
  });

  static Future<ProxyGroupEntry> default_() =>
      RustLib.instance.api.crateApiProxiesCatalogProxyGroupEntryDefault();

  @override
  int get hashCode =>
      name.hashCode ^
      proxyType.hashCode ^
      icon.hashCode ^
      memberCount.hashCode ^
      membersHash.hashCode ^
      now.hashCode ^
      testUrl.hashCode ^
      fixed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyGroupEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          proxyType == other.proxyType &&
          icon == other.icon &&
          memberCount == other.memberCount &&
          membersHash == other.membersHash &&
          now == other.now &&
          testUrl == other.testUrl &&
          fixed == other.fixed;
}

class ProxyMemberEntry {
  final String name;
  final String proxyType;
  final int delay;

  const ProxyMemberEntry({
    required this.name,
    required this.proxyType,
    required this.delay,
  });

  static Future<ProxyMemberEntry> default_() =>
      RustLib.instance.api.crateApiProxiesCatalogProxyMemberEntryDefault();

  @override
  int get hashCode => name.hashCode ^ proxyType.hashCode ^ delay.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyMemberEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          proxyType == other.proxyType &&
          delay == other.delay;
}

enum ProxyMemberSort {
  original,
  name,
  delay;

  static Future<ProxyMemberSort> default_() =>
      RustLib.instance.api.crateApiProxiesCatalogProxyMemberSortDefault();
}
