// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../api.dart';
import '../../frb_generated.dart';
import '../../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `delay_of`, `delay_score`, `history_delay`, `proxy_group_matches`, `push_icon`, `sort_members`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// Structured proxy + group catalog. Rust parses mihomo's `/proxies`, applies
/// hidden-group filtering, preserves UI ordering (`GLOBAL.all`), and returns
/// the node/group index Dart needs.
Future<ProxyCatalog> proxyCatalog({
  required MihomoTarget target,
  required bool includeHidden,
  required String filter,
  required ProxyMemberSort memberSort,
}) => RustLib.instance.api.crateApiProxiesCatalogProxyCatalog(
  target: target,
  includeHidden: includeHidden,
  filter: filter,
  memberSort: memberSort,
);

class ProxyCatalog {
  final List<ProxyGroupEntry> groups;
  final List<ProxyNodeEntry> nodes;
  final List<String> iconUrls;

  const ProxyCatalog({
    required this.groups,
    required this.nodes,
    required this.iconUrls,
  });

  static Future<ProxyCatalog> default_() =>
      RustLib.instance.api.crateApiProxiesCatalogProxyCatalogDefault();

  @override
  int get hashCode => groups.hashCode ^ nodes.hashCode ^ iconUrls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyCatalog &&
          runtimeType == other.runtimeType &&
          groups == other.groups &&
          nodes == other.nodes &&
          iconUrls == other.iconUrls;
}

class ProxyGroupEntry {
  final String name;
  final String proxyType;
  final String icon;
  final List<String> all;
  final String now;
  final String testUrl;
  final String fixed;

  const ProxyGroupEntry({
    required this.name,
    required this.proxyType,
    required this.icon,
    required this.all,
    required this.now,
    required this.testUrl,
    required this.fixed,
  });

  static Future<ProxyGroupEntry> default_() =>
      RustLib.instance.api.crateApiProxiesCatalogProxyGroupEntryDefault();

  @override
  int get hashCode =>
      name.hashCode ^
      proxyType.hashCode ^
      icon.hashCode ^
      all.hashCode ^
      now.hashCode ^
      testUrl.hashCode ^
      fixed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyGroupEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          proxyType == other.proxyType &&
          icon == other.icon &&
          all == other.all &&
          now == other.now &&
          testUrl == other.testUrl &&
          fixed == other.fixed;
}

enum ProxyMemberSort {
  original,
  name,
  delay;

  static Future<ProxyMemberSort> default_() =>
      RustLib.instance.api.crateApiProxiesCatalogProxyMemberSortDefault();
}

class ProxyNodeEntry {
  final String name;
  final String proxyType;
  final String icon;
  final int delay;

  const ProxyNodeEntry({
    required this.name,
    required this.proxyType,
    required this.icon,
    required this.delay,
  });

  static Future<ProxyNodeEntry> default_() =>
      RustLib.instance.api.crateApiProxiesCatalogProxyNodeEntryDefault();

  @override
  int get hashCode =>
      name.hashCode ^ proxyType.hashCode ^ icon.hashCode ^ delay.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyNodeEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          proxyType == other.proxyType &&
          icon == other.icon &&
          delay == other.delay;
}
