// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../api.dart';
import '../../frb_generated.dart';
import '../../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `proxy_delay_with_client`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// `GET /proxies/{name}/delay` — returns the measured delay in ms, or `0` if
/// upstream returned non-success without an HTTP body. `expected_status`
/// follows mihomo's range syntax, e.g. `"200/204/301-302"`.
Future<PlatformInt64> proxyDelay({
  required MihomoTarget target,
  required String name,
  required String testUrl,
  required int timeoutMs,
  String? expectedStatus,
}) => RustLib.instance.api.crateApiProxiesDelayProxyDelay(
  target: target,
  name: name,
  testUrl: testUrl,
  timeoutMs: timeoutMs,
  expectedStatus: expectedStatus,
);

/// Batch variant of [`proxy_delay`]. Individual node failures are reported as
/// `0` (timeout), matching the existing UI behavior for one-off node tests.
Future<List<ProxyDelayEntry>> proxyBatchDelay({
  required MihomoTarget target,
  required List<String> names,
  required String testUrl,
  required int timeoutMs,
  String? expectedStatus,
  required int concurrency,
}) => RustLib.instance.api.crateApiProxiesDelayProxyBatchDelay(
  target: target,
  names: names,
  testUrl: testUrl,
  timeoutMs: timeoutMs,
  expectedStatus: expectedStatus,
  concurrency: concurrency,
);

/// Batch delay test for every cached member of one group. The member list stays
/// in Rust; Dart only receives the delay results.
Future<List<ProxyDelayEntry>> proxyGroupBatchDelay({
  required MihomoTarget target,
  required String group,
  required String testUrl,
  required int timeoutMs,
  String? expectedStatus,
  required int concurrency,
}) => RustLib.instance.api.crateApiProxiesDelayProxyGroupBatchDelay(
  target: target,
  group: group,
  testUrl: testUrl,
  timeoutMs: timeoutMs,
  expectedStatus: expectedStatus,
  concurrency: concurrency,
);

class ProxyDelayEntry {
  final String name;
  final int delay;

  const ProxyDelayEntry({required this.name, required this.delay});

  static Future<ProxyDelayEntry> default_() =>
      RustLib.instance.api.crateApiProxiesDelayProxyDelayEntryDefault();

  @override
  int get hashCode => name.hashCode ^ delay.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyDelayEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          delay == other.delay;
}
