// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import '../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `value_to_string`

/// `GET /configs` — full general config snapshot.
Future<String> configs({required MihomoTarget target}) =>
    RustLib.instance.api.crateApiConfigsConfigs(target: target);

/// `GET /configs` — return only outbound mode, normalized for the launcher.
Future<String> configMode({required MihomoTarget target}) =>
    RustLib.instance.api.crateApiConfigsConfigMode(target: target);

/// `PATCH /configs` — pass-through. The full schema lives in mihomo's
/// [`hub/route/configs.go`](https://github.com/MetaCubeX/mihomo/blob/Alpha/hub/route/configs.go);
/// callers send any subset of those keys (`mode`, `log-level`, `allow-lan`,
/// `port`, `socks-port`, `mixed-port`, `redir-port`, `tproxy-port`,
/// `bind-address`, `ipv6`, `sniffing`, `tcp-concurrent`, `interface-name`,
/// `find-process-mode`, `skip-auth-prefixes`, `lan-allowed-ips`,
/// `lan-disallowed-ips`, `tun`, `tuic-server`, `ss-config`, `vmess-config`,
/// `tcptun-config`, `udptun-config`).
Future<void> patchConfigs({
  required MihomoTarget target,
  required String bodyJson,
}) => RustLib.instance.api.crateApiConfigsPatchConfigs(
  target: target,
  bodyJson: bodyJson,
);

/// `PUT /configs` — reload. `path` must be absolute on the mihomo host (and
/// pass mihomo's `IsSafePath` whitelist), or pass `payload` for inline YAML.
Future<void> reloadConfigs({
  required MihomoTarget target,
  String? path,
  String? payload,
  required bool force,
}) => RustLib.instance.api.crateApiConfigsReloadConfigs(
  target: target,
  path: path,
  payload: payload,
  force: force,
);

/// `POST /configs/geo` — refresh geo databases (forbidden on `--embed`).
Future<void> updateGeo({required MihomoTarget target}) =>
    RustLib.instance.api.crateApiConfigsUpdateGeo(target: target);
