// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import '../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `close_connections_matching`, `conn_in_group`, `conn_uses_chain`

/// `GET /connections` — one snapshot of currently tracked connections.
Future<String> connections({required MihomoTarget target}) =>
    RustLib.instance.api.crateApiConnectionsConnections(target: target);

/// `DELETE /connections/{id}` — close a single connection by UUID.
Future<void> closeConnection({
  required MihomoTarget target,
  required String id,
}) => RustLib.instance.api.crateApiConnectionsCloseConnection(
  target: target,
  id: id,
);

/// `DELETE /connections` — close every tracked connection.
Future<void> closeAllConnections({required MihomoTarget target}) =>
    RustLib.instance.api.crateApiConnectionsCloseAllConnections(target: target);

/// Close every connection whose proxy chain includes `chain`.
///
/// mihomo has no native "close by group" endpoint, so we snapshot
/// `/connections`, filter client-side, and fan out parallel DELETEs.
/// Returns the number of connections that were targeted (best effort —
/// individual closes may fail silently if the connection just ended).
Future<int> closeConnectionsByChain({
  required MihomoTarget target,
  required String chain,
}) => RustLib.instance.api.crateApiConnectionsCloseConnectionsByChain(
  target: target,
  chain: chain,
);

/// Close every connection in a process group. `group` is the same key the
/// grouped view uses: a process name, or a source IP when the process is
/// unknown. Snapshots `/connections`, filters client-side, fans out
/// parallel DELETEs. Returns the number targeted (best effort).
Future<int> closeConnectionsByGroup({
  required MihomoTarget target,
  required String group,
}) => RustLib.instance.api.crateApiConnectionsCloseConnectionsByGroup(
  target: target,
  group: group,
);
