// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import '../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// `GET /dns/query?name=&type=` — perform a DNS query through mihomo's
/// resolver. The response follows the DOH JSON shape (`Status`, `Question`,
/// `Answer`, etc.). Returns 500 if the DNS section is disabled upstream.
Future<String> dnsQuery({
  required MihomoTarget target,
  required String name,
  String? recordType,
}) => RustLib.instance.api.crateApiDnsDnsQuery(
  target: target,
  name: name,
  recordType: recordType,
);
