// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Distinct installed UI font family names, sorted. Empty on Android (which
/// uses the system font). Runs on the blocking pool — scanning the font
/// directories touches the filesystem.
Future<List<String>> systemFontFamilies() =>
    RustLib.instance.api.crateApiFontsSystemFontFamilies();
