// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import '../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `value_to_i32`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// `GET /group` — only proxy groups, in stable order.
Future<String> groups({required MihomoTarget target}) =>
    RustLib.instance.api.crateApiGroupsGroups(target: target);

/// `GET /group/{name}/delay` — runs a parallel URL test for every node in the
/// group and returns the resulting per-node delays.
///
/// **Side effect (mihomo behavior):** for non-Selector groups (URLTest,
/// Fallback, etc.) the call clears the persisted "fixed" selection before
/// running the test.
Future<List<GroupDelayEntry>> groupDelay({
  required MihomoTarget target,
  required String group,
  required String testUrl,
  required int timeoutMs,
  String? expectedStatus,
}) => RustLib.instance.api.crateApiGroupsGroupDelay(
  target: target,
  group: group,
  testUrl: testUrl,
  timeoutMs: timeoutMs,
  expectedStatus: expectedStatus,
);

class GroupDelayEntry {
  final String name;
  final int delay;

  const GroupDelayEntry({required this.name, required this.delay});

  static Future<GroupDelayEntry> default_() =>
      RustLib.instance.api.crateApiGroupsGroupDelayEntryDefault();

  @override
  int get hashCode => name.hashCode ^ delay.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupDelayEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          delay == other.delay;
}
