// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Open the shared cache database and initialize both icon subsystems.
/// Idempotent; the path is fixed on first call.
Future<void> initCache({required String cacheDir}) =>
    RustLib.instance.api.crateApiIconsInitCache(cacheDir: cacheDir);

Future<Uint8List> fetchIcon({required String url}) =>
    RustLib.instance.api.crateApiIconsFetchIcon(url: url);

Future<Uint8List?> fetchProcessIcon({required String path, int? size}) =>
    RustLib.instance.api.crateApiIconsFetchProcessIcon(path: path, size: size);

Future<Uint8List?> cachedProcessIcon({required String key, int? size}) =>
    RustLib.instance.api.crateApiIconsCachedProcessIcon(key: key, size: size);

Future<void> storeProcessIcon({
  required String key,
  required List<int> bytes,
}) =>
    RustLib.instance.api.crateApiIconsStoreProcessIcon(key: key, bytes: bytes);

Future<String?> fetchProcessName({required String path}) =>
    RustLib.instance.api.crateApiIconsFetchProcessName(path: path);

Future<String?> cachedProcessName({required String key}) =>
    RustLib.instance.api.crateApiIconsCachedProcessName(key: key);

Future<void> storeProcessName({required String key, required String name}) =>
    RustLib.instance.api.crateApiIconsStoreProcessName(key: key, name: name);

Future<void> resetProcessIconMisses() =>
    RustLib.instance.api.crateApiIconsResetProcessIconMisses();

/// Total size of the on-disk cache in bytes (keys + values across tables).
Future<BigInt> iconCacheSize() =>
    RustLib.instance.api.crateApiIconsIconCacheSize();

/// Wipe every cached icon and name, then drop the in-memory resolve state so
/// fresh lookups don't surface stale negatives.
Future<void> clearIconCache() =>
    RustLib.instance.api.crateApiIconsClearIconCache();
