// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import '../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `field_or`, `value_to_string`, `value_to_u32`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<String> proxyProviders({required MihomoTarget target}) =>
    RustLib.instance.api.crateApiProvidersProxyProviders(target: target);

Future<List<ProxyProviderEntry>> proxyProviderCatalog({
  required MihomoTarget target,
}) =>
    RustLib.instance.api.crateApiProvidersProxyProviderCatalog(target: target);

Future<void> proxyProviderUpdate({
  required MihomoTarget target,
  required String name,
}) => RustLib.instance.api.crateApiProvidersProxyProviderUpdate(
  target: target,
  name: name,
);

Future<void> proxyProviderHealthcheck({
  required MihomoTarget target,
  required String name,
}) => RustLib.instance.api.crateApiProvidersProxyProviderHealthcheck(
  target: target,
  name: name,
);

Future<String> ruleProviders({required MihomoTarget target}) =>
    RustLib.instance.api.crateApiProvidersRuleProviders(target: target);

Future<List<RuleProviderEntry>> ruleProviderCatalog({
  required MihomoTarget target,
}) => RustLib.instance.api.crateApiProvidersRuleProviderCatalog(target: target);

Future<void> ruleProviderUpdate({
  required MihomoTarget target,
  required String name,
}) => RustLib.instance.api.crateApiProvidersRuleProviderUpdate(
  target: target,
  name: name,
);

class ProxyProviderEntry {
  final String name;
  final String vehicleType;
  final int proxies;
  final String updatedAt;
  final bool updatable;

  const ProxyProviderEntry({
    required this.name,
    required this.vehicleType,
    required this.proxies,
    required this.updatedAt,
    required this.updatable,
  });

  static Future<ProxyProviderEntry> default_() =>
      RustLib.instance.api.crateApiProvidersProxyProviderEntryDefault();

  @override
  int get hashCode =>
      name.hashCode ^
      vehicleType.hashCode ^
      proxies.hashCode ^
      updatedAt.hashCode ^
      updatable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyProviderEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          vehicleType == other.vehicleType &&
          proxies == other.proxies &&
          updatedAt == other.updatedAt &&
          updatable == other.updatable;
}

class RuleProviderEntry {
  final String name;
  final String vehicleType;
  final String behavior;
  final String format;
  final int ruleCount;
  final String updatedAt;
  final bool updatable;

  const RuleProviderEntry({
    required this.name,
    required this.vehicleType,
    required this.behavior,
    required this.format,
    required this.ruleCount,
    required this.updatedAt,
    required this.updatable,
  });

  static Future<RuleProviderEntry> default_() =>
      RustLib.instance.api.crateApiProvidersRuleProviderEntryDefault();

  @override
  int get hashCode =>
      name.hashCode ^
      vehicleType.hashCode ^
      behavior.hashCode ^
      format.hashCode ^
      ruleCount.hashCode ^
      updatedAt.hashCode ^
      updatable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuleProviderEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          vehicleType == other.vehicleType &&
          behavior == other.behavior &&
          format == other.format &&
          ruleCount == other.ruleCount &&
          updatedAt == other.updatedAt &&
          updatable == other.updatable;
}
