// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import '../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// `GET /proxies` — full proxy + group catalog. Optional regex filters keep
/// the wire small when the controller is remote.
Future<String> proxies({
  required MihomoTarget target,
  String? namePattern,
  String? typePattern,
  required bool groupsOnly,
}) => RustLib.instance.api.crateApiProxiesProxies(
  target: target,
  namePattern: namePattern,
  typePattern: typePattern,
  groupsOnly: groupsOnly,
);

Future<String> proxyDetail({
  required MihomoTarget target,
  required String name,
}) =>
    RustLib.instance.api.crateApiProxiesProxyDetail(target: target, name: name);

Future<void> selectProxy({
  required MihomoTarget target,
  required String group,
  required String name,
}) => RustLib.instance.api.crateApiProxiesSelectProxy(
  target: target,
  group: group,
  name: name,
);

/// `DELETE /proxies/{name}` — clears the "fixed" selection on a non-Selector group.
Future<void> unfixProxy({required MihomoTarget target, required String name}) =>
    RustLib.instance.api.crateApiProxiesUnfixProxy(target: target, name: name);
