// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import '../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cache`, `parse_rule`, `recompute`, `rule_matches`, `summary`, `take_str`, `target_key`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RulesCache`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// `GET /rules` — count only. Fetches the ruleset and returns its length
/// without touching the paging cache, so a session-level badge probe can't
/// clobber the rules screen's active filter. Returns 0 on any error.
Future<int> rulesCount({required MihomoTarget target}) =>
    RustLib.instance.api.crateApiRulesRulesCount(target: target);

/// `GET /rules` — fetch the full ruleset, cache it for `target`, apply
/// `filter`, and return counts. Replaces any previously cached ruleset.
Future<RulesSummary> rulesLoad({
  required MihomoTarget target,
  required String filter,
}) =>
    RustLib.instance.api.crateApiRulesRulesLoad(target: target, filter: filter);

/// Re-filter the cached ruleset for `target` without re-fetching. Returns the
/// updated counts, or zeros if no ruleset is cached for this target.
Future<RulesSummary> rulesSetFilter({
  required MihomoTarget target,
  required String filter,
}) => RustLib.instance.api.crateApiRulesRulesSetFilter(
  target: target,
  filter: filter,
);

/// Slice the filtered view at `[offset, offset + limit)`. Bounds-checked;
/// returns fewer than `limit` near the tail, or empty if no matching cache.
Future<List<RuleEntry>> rulesWindow({
  required MihomoTarget target,
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateApiRulesRulesWindow(
  target: target,
  offset: offset,
  limit: limit,
);

/// `PATCH /rules/disable` — toggle rules by index. Body is `{<index>: bool}`.
/// On success the cache is patched so the next window reflects the change
/// without a reload. mihomo rejects this under `--embed`; treat 404 as a
/// feature gate, not a bug.
Future<void> rulesDisable({
  required MihomoTarget target,
  required String indicesJson,
}) => RustLib.instance.api.crateApiRulesRulesDisable(
  target: target,
  indicesJson: indicesJson,
);

/// One routing rule. `has_extra` is true when the core returned the `extra`
/// block (hit stats + disable support); it gates the per-rule toggle in the UI.
class RuleEntry {
  final int index;
  final String ruleType;
  final String payload;
  final String proxy;
  final bool disabled;
  final BigInt hitCount;
  final BigInt missCount;
  final bool hasExtra;

  const RuleEntry({
    required this.index,
    required this.ruleType,
    required this.payload,
    required this.proxy,
    required this.disabled,
    required this.hitCount,
    required this.missCount,
    required this.hasExtra,
  });

  static Future<RuleEntry> default_() =>
      RustLib.instance.api.crateApiRulesRuleEntryDefault();

  @override
  int get hashCode =>
      index.hashCode ^
      ruleType.hashCode ^
      payload.hashCode ^
      proxy.hashCode ^
      disabled.hashCode ^
      hitCount.hashCode ^
      missCount.hashCode ^
      hasExtra.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuleEntry &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          ruleType == other.ruleType &&
          payload == other.payload &&
          proxy == other.proxy &&
          disabled == other.disabled &&
          hitCount == other.hitCount &&
          missCount == other.missCount &&
          hasExtra == other.hasExtra;
}

/// Counts returned to Dart after a load or filter change. `total` is the full
/// ruleset size; `filtered` is how many survive the current filter.
class RulesSummary {
  final int total;
  final int filtered;

  const RulesSummary({required this.total, required this.filtered});

  static Future<RulesSummary> default_() =>
      RustLib.instance.api.crateApiRulesRulesSummaryDefault();

  @override
  int get hashCode => total.hashCode ^ filtered.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RulesSummary &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          filtered == other.filtered;
}
