// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import '../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// `GET /storage/{key}` — returns a JSON value, or the literal string
/// `"null"` when the key has never been written.
Future<String> storageGet({
  required MihomoTarget target,
  required String key,
}) => RustLib.instance.api.crateApiStorageStorageGet(target: target, key: key);

/// `PUT /storage/{key}` — store a JSON value. mihomo enforces a 1 MiB cap and
/// rejects bodies that aren't valid JSON.
Future<void> storageSet({
  required MihomoTarget target,
  required String key,
  required String valueJson,
}) => RustLib.instance.api.crateApiStorageStorageSet(
  target: target,
  key: key,
  valueJson: valueJson,
);

/// `DELETE /storage/{key}` — remove a key (always 204 even if absent).
Future<void> storageDelete({
  required MihomoTarget target,
  required String key,
}) =>
    RustLib.instance.api.crateApiStorageStorageDelete(target: target, key: key);
