// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import '../state/connections/types.dart';
import '../state/logs.dart';
import '../state/traffic.dart';
import '../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Subscribe to mihomo's `/traffic` WebSocket feed (1Hz).
Stream<TrafficSample> trafficStream({required MihomoTarget target}) =>
    RustLib.instance.api.crateApiStreamsTrafficStream(target: target);

/// Subscribe to mihomo's `/memory` WebSocket feed (1Hz).
Stream<MemorySample> memoryStream({required MihomoTarget target}) =>
    RustLib.instance.api.crateApiStreamsMemoryStream(target: target);

/// Subscribe to mihomo's `/logs?level=&format=structured` feed.
///
/// The stream first replays up to `LOGS_CAP` cached entries as one batch, then
/// continues with small live batches. Snapshot + stream are taken under the
/// same lock, so no entries are dropped or duplicated across the boundary.
Stream<List<LogEntry>> logsStream({
  required MihomoTarget target,
  required String level,
}) => RustLib.instance.api.crateApiStreamsLogsStream(
  target: target,
  level: level,
);

/// Drop the cached log buffer for `(target, level)`. The upstream stream
/// keeps running so new lines flow normally.
Future<void> clearLogs({required MihomoTarget target, required String level}) =>
    RustLib.instance.api.crateApiStreamsClearLogs(target: target, level: level);

/// Subscribe to mihomo's `/connections?interval=<ms>` WebSocket feed.
///
/// Each frame carries totals and the active/closed counts. Dart pages
/// the row payloads it actually needs via [`fetch_connection_window`].
Stream<ConnectionsFrame> connectionsStream({
  required MihomoTarget target,
  required int intervalMs,
}) => RustLib.instance.api.crateApiStreamsConnectionsStream(
  target: target,
  intervalMs: intervalMs,
);

/// Page a slice of the sorted connections list. `kind` picks active vs
/// closed; `offset`/`limit` are bounds-checked.
Future<List<Connection>> fetchConnectionWindow({
  required MihomoTarget target,
  required int intervalMs,
  required ConnectionsListKind kind,
  required int offset,
  required int limit,
}) => RustLib.instance.api.crateApiStreamsFetchConnectionWindow(
  target: target,
  intervalMs: intervalMs,
  kind: kind,
  offset: offset,
  limit: limit,
);

/// Aggregate active connections into per-process groups (process name, or
/// source IP when unknown), ordered by `sort`.
Future<List<ConnectionGroup>> fetchConnectionGroups({
  required MihomoTarget target,
  required int intervalMs,
  required ConnectionGroupSort sort,
  required bool asc,
}) => RustLib.instance.api.crateApiStreamsFetchConnectionGroups(
  target: target,
  intervalMs: intervalMs,
  sort: sort,
  asc: asc,
);

/// Active connections belonging to `group`, sorted and capped at `limit`.
Future<List<Connection>> fetchConnectionGroupMembers({
  required MihomoTarget target,
  required int intervalMs,
  required String group,
  required int limit,
}) => RustLib.instance.api.crateApiStreamsFetchConnectionGroupMembers(
  target: target,
  intervalMs: intervalMs,
  group: group,
  limit: limit,
);

/// Update the per-target sort key. Effective from the next emitted frame.
Future<void> setConnectionsSort({
  required MihomoTarget target,
  required int intervalMs,
  required ConnectionsSort sort,
  required bool asc,
}) => RustLib.instance.api.crateApiStreamsSetConnectionsSort(
  target: target,
  intervalMs: intervalMs,
  sort: sort,
  asc: asc,
);

/// Drop the closed-connections FIFO buffer for the given target/interval.
/// The next emitted frame will report `closed_count = 0`.
Future<void> clearClosedConnections({
  required MihomoTarget target,
  required int intervalMs,
}) => RustLib.instance.api.crateApiStreamsClearClosedConnections(
  target: target,
  intervalMs: intervalMs,
);

/// Signal every background stream (traffic/memory/connections/logs) for
/// `target` to tear down its upstream WebSocket now. Dart calls this when
/// switching away from or removing a backend: frb won't abort the Rust stream
/// task on subscription-cancel, and a dead upstream emits no frame to trip the
/// sink-closed path, so without this the old loops would retry the dead
/// backend forever.
Future<void> stopTargetStreams({required MihomoTarget target}) =>
    RustLib.instance.api.crateApiStreamsStopTargetStreams(target: target);
