// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import '../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// `POST /upgrade/` — pull the latest mihomo core for the requested release
/// channel and **restart the upstream process** on success. Forbidden when
/// the controller was started with `--embed`.
Future<void> upgradeCore({
  required MihomoTarget target,
  String? channel,
  required bool force,
}) => RustLib.instance.api.crateApiUpgradeUpgradeCore(
  target: target,
  channel: channel,
  force: force,
);

/// `POST /upgrade/ui` — fetch the latest dashboard bundle to mihomo's
/// `external-ui` directory.
Future<void> upgradeUi({required MihomoTarget target}) =>
    RustLib.instance.api.crateApiUpgradeUpgradeUi(target: target);

/// `POST /upgrade/geo` — refresh GeoIP / GeoSite databases. Forbidden on
/// `--embed`.
Future<void> upgradeGeo({required MihomoTarget target}) =>
    RustLib.instance.api.crateApiUpgradeUpgradeGeo(target: target);

/// `POST /restart` — restart the upstream mihomo process. Forbidden on
/// `--embed`. Returns immediately (the actual exec happens asynchronously),
/// so subsequent calls will fail until mihomo is reachable again.
Future<void> restartCore({required MihomoTarget target}) =>
    RustLib.instance.api.crateApiUpgradeRestartCore(target: target);
