// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import '../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// `GET /version` → `{version, meta}`.
Future<String> version({required MihomoTarget target}) =>
    RustLib.instance.api.crateApiVersionVersion(target: target);

Future<VersionInfo> versionInfo({required MihomoTarget target}) =>
    RustLib.instance.api.crateApiVersionVersionInfo(target: target);

class VersionInfo {
  final String version;
  final bool isCmfa;

  const VersionInfo({required this.version, required this.isCmfa});

  static Future<VersionInfo> default_() =>
      RustLib.instance.api.crateApiVersionVersionInfoDefault();

  @override
  int get hashCode => version.hashCode ^ isCmfa.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VersionInfo &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          isCmfa == other.isCmfa;
}
