// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import '../utils/error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `info_from_probe`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Raw version endpoint, with Stash falling back to `/`.
Future<String> version({required MihomoTarget target}) =>
    RustLib.instance.api.crateApiVersionVersion(target: target);

Future<VersionInfo> versionInfo({required MihomoTarget target}) =>
    RustLib.instance.api.crateApiVersionVersionInfo(target: target);

class VersionInfo {
  final String version;
  final bool isCmfa;
  final bool isStash;
  final bool supportsCoreConfig;
  final bool supportsCoreActions;
  final bool supportsCoreManagement;
  final bool supportsCacheFlush;
  final bool supportsMemory;

  const VersionInfo({
    required this.version,
    required this.isCmfa,
    required this.isStash,
    required this.supportsCoreConfig,
    required this.supportsCoreActions,
    required this.supportsCoreManagement,
    required this.supportsCacheFlush,
    required this.supportsMemory,
  });

  static Future<VersionInfo> default_() =>
      RustLib.instance.api.crateApiVersionVersionInfoDefault();

  @override
  int get hashCode =>
      version.hashCode ^
      isCmfa.hashCode ^
      isStash.hashCode ^
      supportsCoreConfig.hashCode ^
      supportsCoreActions.hashCode ^
      supportsCoreManagement.hashCode ^
      supportsCacheFlush.hashCode ^
      supportsMemory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VersionInfo &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          isCmfa == other.isCmfa &&
          isStash == other.isStash &&
          supportsCoreConfig == other.supportsCoreConfig &&
          supportsCoreActions == other.supportsCoreActions &&
          supportsCoreManagement == other.supportsCoreManagement &&
          supportsCacheFlush == other.supportsCacheFlush &&
          supportsMemory == other.supportsMemory;
}
