// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class MihomoError with _$MihomoError implements FrbException {
  const MihomoError._();

  const factory MihomoError.invalidUrl(String field0) = MihomoError_InvalidUrl;
  const factory MihomoError.invalidRegex({
    required String pattern,
    required String message,
  }) = MihomoError_InvalidRegex;
  const factory MihomoError.upstream({
    required int status,
    required String body,
  }) = MihomoError_Upstream;
  const factory MihomoError.network(String field0) = MihomoError_Network;
  const factory MihomoError.invalidJson(String field0) =
      MihomoError_InvalidJson;
  const factory MihomoError.other(String field0) = MihomoError_Other;
}
