name: Build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  verify-generated-bindings:
    uses: ./.github/workflows/verify-generated-bindings.yml

  android:
    uses: ./.github/workflows/build-android.yml
    secrets: inherit

  linux:
    uses: ./.github/workflows/build-linux.yml

  windows:
    uses: ./.github/workflows/build-windows.yml

  apple:
    uses: ./.github/workflows/build-apple.yml
