name: TestFlight

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

concurrency:
  group: testflight
  cancel-in-progress: false

jobs:
  build-ios:
    name: Build iOS
    uses: ./.github/workflows/build-ios.yml
    with:
      update_channel: beta
      include_xcarchive: true

  push:
    name: Push TestFlight
    needs: build-ios
    uses: ./.github/workflows/publish-testflight.yml
    with:
      source_path: .github/workflows/testflight.yml
    secrets: inherit

  cleanup-cache:
    name: Cache GC
    if: always()
    needs: build-ios
    uses: ./.github/workflows/cleanup-cache.yml
    with:
      run_id: ${{ github.run_id }}
      cache_key_pattern: 'v1-rust-ios|pub-ios'
    secrets: inherit
